package com.custom.keyboard.emoticon.categories;

import com.custom.keyboard.emoticon.Emoticon;

public class ActivitiesCategory {
    public static final Emoticon[] Data = new Emoticon[] {
        Emoticon.fromCodePoints(0x1f383),
        Emoticon.fromCodePoints(0x1f384),
        Emoticon.fromCodePoints(0x1f386),
        Emoticon.fromCodePoints(0x1f387),
        Emoticon.fromCodePoints(0x1f9e8),
        Emoticon.fromCodePoints(0x2728),
        Emoticon.fromCodePoints(0x1f388),
        Emoticon.fromCodePoints(0x1f389),
        Emoticon.fromCodePoints(0x1f38a),
        Emoticon.fromCodePoints(0x1f38b),
        Emoticon.fromCodePoints(0x1f38d),
        Emoticon.fromCodePoints(0x1f38e),
        Emoticon.fromCodePoints(0x1f38f),
        Emoticon.fromCodePoints(0x1f390),
        Emoticon.fromCodePoints(0x1f391),
        Emoticon.fromCodePoints(0x1f9e7),
        Emoticon.fromCodePoints(0x1f380),
        Emoticon.fromCodePoints(0x1f381),
        Emoticon.fromCodePoints(0x1f397, 0xfe0f),
        Emoticon.fromCodePoints(0x1f39f, 0xfe0f),
        Emoticon.fromCodePoints(0x1f3ab),
        Emoticon.fromCodePoints(0x1f396, 0xfe0f),
        Emoticon.fromCodePoints(0x1f3c6),
        Emoticon.fromCodePoints(0x1f3c5),
        Emoticon.fromCodePoints(0x1f947),
        Emoticon.fromCodePoints(0x1f948),
        Emoticon.fromCodePoints(0x1f949),
        Emoticon.fromCodePoints(0x26bd),
        Emoticon.fromCodePoints(0x26be),
        Emoticon.fromCodePoints(0x1f94e),
        Emoticon.fromCodePoints(0x1f3c0),
        Emoticon.fromCodePoints(0x1f3d0),
        Emoticon.fromCodePoints(0x1f3c8),
        Emoticon.fromCodePoints(0x1f3c9),
        Emoticon.fromCodePoints(0x1f3be),
        Emoticon.fromCodePoints(0x1f94f),
        Emoticon.fromCodePoints(0x1f3b3),
        Emoticon.fromCodePoints(0x1f3cf),
        Emoticon.fromCodePoints(0x1f3d1),
        Emoticon.fromCodePoints(0x1f3d2),
        Emoticon.fromCodePoints(0x1f94d),
        Emoticon.fromCodePoints(0x1f3d3),
        Emoticon.fromCodePoints(0x1f3f8),
        Emoticon.fromCodePoints(0x1f94a),
        Emoticon.fromCodePoints(0x1f94b),
        Emoticon.fromCodePoints(0x1f945),
        Emoticon.fromCodePoints(0x26f3),
        Emoticon.fromCodePoints(0x26f8, 0xfe0f),
        Emoticon.fromCodePoints(0x1f3a3),
        Emoticon.fromCodePoints(0x1f93f),
        Emoticon.fromCodePoints(0x1f3bd),
        Emoticon.fromCodePoints(0x1f3bf),
        Emoticon.fromCodePoints(0x1f6f7),
        Emoticon.fromCodePoints(0x1f94c),
        Emoticon.fromCodePoints(0x1f3af),
        Emoticon.fromCodePoints(0x1fa80),
        Emoticon.fromCodePoints(0x1fa81),
        Emoticon.fromCodePoints(0x1f3b1),
        Emoticon.fromCodePoints(0x1f52e),
        Emoticon.fromCodePoints(0x1f9ff),
        Emoticon.fromCodePoints(0x1f3ae),
        Emoticon.fromCodePoints(0x1f579, 0xfe0f),
        Emoticon.fromCodePoints(0x1f3b0),
        Emoticon.fromCodePoints(0x1f3b2),
        Emoticon.fromCodePoints(0x1f9e9),
        Emoticon.fromCodePoints(0x1f9f8),
        Emoticon.fromCodePoints(0x2660, 0xfe0f),
        Emoticon.fromCodePoints(0x2665, 0xfe0f),
        Emoticon.fromCodePoints(0x2666, 0xfe0f),
        Emoticon.fromCodePoints(0x2663, 0xfe0f),
        Emoticon.fromCodePoints(0x265f, 0xfe0f),
        Emoticon.fromCodePoints(0x1f0cf),
        Emoticon.fromCodePoints(0x1f004),
        Emoticon.fromCodePoints(0x1f3b4),
        Emoticon.fromCodePoints(0x1f3ad),
        Emoticon.fromCodePoints(0x1f5bc, 0xfe0f),
        Emoticon.fromCodePoints(0x1f3a8),
        Emoticon.fromCodePoints(0x1f9f5),
        Emoticon.fromCodePoints(0x1f9f6)
    };
}
