package com.custom.keyboard.emoticon.categories;

import com.custom.keyboard.emoticon.Emoticon;

public class ObjectsCategory {

    public static final Emoticon[] Data = new Emoticon[] {
        Emoticon.fromCodePoints(0x1f453),
        Emoticon.fromCodePoints(0x1f576, 0xfe0f),
        Emoticon.fromCodePoints(0x1f97d),
        Emoticon.fromCodePoints(0x1f97c),
        // Emoticon.fromCodePoints(0x1f9ba),
        Emoticon.fromCodePoints(0x1f454),
        Emoticon.fromCodePoints(0x1f455),
        Emoticon.fromCodePoints(0x1f456),
        Emoticon.fromCodePoints(0x1f9e3),
        Emoticon.fromCodePoints(0x1f9e4),
        Emoticon.fromCodePoints(0x1f9e5),
        Emoticon.fromCodePoints(0x1f9e6),
        Emoticon.fromCodePoints(0x1f457),
        Emoticon.fromCodePoints(0x1f458),
        // Emoticon.fromCodePoints(0x1f97b),
        // Emoticon.fromCodePoints(0x1fa71),
        // Emoticon.fromCodePoints(0x1fa72),
        // Emoticon.fromCodePoints(0x1fa73),
        Emoticon.fromCodePoints(0x1f459),
        Emoticon.fromCodePoints(0x1f45a),
        Emoticon.fromCodePoints(0x1f45b),
        Emoticon.fromCodePoints(0x1f45c),
        Emoticon.fromCodePoints(0x1f45d),
        Emoticon.fromCodePoints(0x1f6cd, 0xfe0f),
        Emoticon.fromCodePoints(0x1f392),
        Emoticon.fromCodePoints(0x1f45e),
        Emoticon.fromCodePoints(0x1f45f),
        Emoticon.fromCodePoints(0x1f97e),
        Emoticon.fromCodePoints(0x1f97f),
        Emoticon.fromCodePoints(0x1f460),
        Emoticon.fromCodePoints(0x1f461),
        Emoticon.fromCodePoints(0x1fa70),
        Emoticon.fromCodePoints(0x1f462),
        Emoticon.fromCodePoints(0x1f451),
        Emoticon.fromCodePoints(0x1f452),
        Emoticon.fromCodePoints(0x1f3a9),
        Emoticon.fromCodePoints(0x1f393),
        Emoticon.fromCodePoints(0x1f9e2),
        Emoticon.fromCodePoints(0x26d1, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4ff),
        Emoticon.fromCodePoints(0x1f484),
        Emoticon.fromCodePoints(0x1f48d),
        Emoticon.fromCodePoints(0x1f48e),
        Emoticon.fromCodePoints(0x1f507),
        Emoticon.fromCodePoints(0x1f508),
        Emoticon.fromCodePoints(0x1f509),
        Emoticon.fromCodePoints(0x1f50a),
        Emoticon.fromCodePoints(0x1f4e2),
        Emoticon.fromCodePoints(0x1f4e3),
        Emoticon.fromCodePoints(0x1f4ef),
        Emoticon.fromCodePoints(0x1f514),
        Emoticon.fromCodePoints(0x1f515),
        Emoticon.fromCodePoints(0x1f3bc),
        Emoticon.fromCodePoints(0x1f3b5),
        Emoticon.fromCodePoints(0x1f3b6),
        Emoticon.fromCodePoints(0x1f399, 0xfe0f),
        Emoticon.fromCodePoints(0x1f39a, 0xfe0f),
        Emoticon.fromCodePoints(0x1f39b, 0xfe0f),
        Emoticon.fromCodePoints(0x1f3a4),
        Emoticon.fromCodePoints(0x1f3a7),
        Emoticon.fromCodePoints(0x1f4fb),
        Emoticon.fromCodePoints(0x1f3b7),
        Emoticon.fromCodePoints(0x1f3b8),
        Emoticon.fromCodePoints(0x1f3b9),
        Emoticon.fromCodePoints(0x1f3ba),
        Emoticon.fromCodePoints(0x1f3bb),
        Emoticon.fromCodePoints(0x1fa95),
        Emoticon.fromCodePoints(0x1f941),
        Emoticon.fromCodePoints(0x1f4f1),
        Emoticon.fromCodePoints(0x1f4f2),
        Emoticon.fromCodePoints(0x260e, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4de),
        Emoticon.fromCodePoints(0x1f4df),
        Emoticon.fromCodePoints(0x1f4e0),
        Emoticon.fromCodePoints(0x1f50b),
        Emoticon.fromCodePoints(0x1f50c),
        Emoticon.fromCodePoints(0x1f4bb),
        Emoticon.fromCodePoints(0x1f5a5, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5a8, 0xfe0f),
        Emoticon.fromCodePoints(0x2328, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5b1, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5b2, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4bd),
        Emoticon.fromCodePoints(0x1f4be),
        Emoticon.fromCodePoints(0x1f4bf),
        Emoticon.fromCodePoints(0x1f4c0),
        Emoticon.fromCodePoints(0x1f9ee),
        Emoticon.fromCodePoints(0x1f3a5),
        Emoticon.fromCodePoints(0x1f39e, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4fd, 0xfe0f),
        Emoticon.fromCodePoints(0x1f3ac),
        Emoticon.fromCodePoints(0x1f4fa),
        Emoticon.fromCodePoints(0x1f4f7),
        Emoticon.fromCodePoints(0x1f4f8),
        Emoticon.fromCodePoints(0x1f4f9),
        Emoticon.fromCodePoints(0x1f4fc),
        Emoticon.fromCodePoints(0x1f50d),
        Emoticon.fromCodePoints(0x1f50e),
        Emoticon.fromCodePoints(0x1f56f, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4a1),
        Emoticon.fromCodePoints(0x1f526),
        Emoticon.fromCodePoints(0x1f3ee),
        Emoticon.fromCodePoints(0x1fa94),
        Emoticon.fromCodePoints(0x1f4d4),
        Emoticon.fromCodePoints(0x1f4d5),
        Emoticon.fromCodePoints(0x1f4d6),
        Emoticon.fromCodePoints(0x1f4d7),
        Emoticon.fromCodePoints(0x1f4d8),
        Emoticon.fromCodePoints(0x1f4d9),
        Emoticon.fromCodePoints(0x1f4da),
        Emoticon.fromCodePoints(0x1f4d3),
        Emoticon.fromCodePoints(0x1f4d2),
        Emoticon.fromCodePoints(0x1f4c3),
        Emoticon.fromCodePoints(0x1f4dc),
        Emoticon.fromCodePoints(0x1f4c4),
        Emoticon.fromCodePoints(0x1f4f0),
        Emoticon.fromCodePoints(0x1f5de, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4d1),
        Emoticon.fromCodePoints(0x1f516),
        Emoticon.fromCodePoints(0x1f3f7, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4b0),
        Emoticon.fromCodePoints(0x1f4b4),
        Emoticon.fromCodePoints(0x1f4b5),
        Emoticon.fromCodePoints(0x1f4b6),
        Emoticon.fromCodePoints(0x1f4b7),
        Emoticon.fromCodePoints(0x1f4b8),
        Emoticon.fromCodePoints(0x1f4b3),
        Emoticon.fromCodePoints(0x1f9fe),
        Emoticon.fromCodePoints(0x1f4b9),
        Emoticon.fromCodePoints(0x1f4b1),
        Emoticon.fromCodePoints(0x1f4b2),
        Emoticon.fromCodePoints(0x2709, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4e7),
        Emoticon.fromCodePoints(0x1f4e8),
        Emoticon.fromCodePoints(0x1f4e9),
        Emoticon.fromCodePoints(0x1f4e4),
        Emoticon.fromCodePoints(0x1f4e5),
        Emoticon.fromCodePoints(0x1f4e6),
        Emoticon.fromCodePoints(0x1f4eb),
        Emoticon.fromCodePoints(0x1f4ea),
        Emoticon.fromCodePoints(0x1f4ec),
        Emoticon.fromCodePoints(0x1f4ed),
        Emoticon.fromCodePoints(0x1f4ee),
        Emoticon.fromCodePoints(0x1f5f3, 0xfe0f),
        Emoticon.fromCodePoints(0x270f, 0xfe0f),
        Emoticon.fromCodePoints(0x2712, 0xfe0f),
        Emoticon.fromCodePoints(0x1f58b, 0xfe0f),
        Emoticon.fromCodePoints(0x1f58a, 0xfe0f),
        Emoticon.fromCodePoints(0x1f58c, 0xfe0f),
        Emoticon.fromCodePoints(0x1f58d, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4dd),
        Emoticon.fromCodePoints(0x1f4bc),
        Emoticon.fromCodePoints(0x1f4c1),
        Emoticon.fromCodePoints(0x1f4c2),
        Emoticon.fromCodePoints(0x1f5c2, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4c5),
        Emoticon.fromCodePoints(0x1f4c6),
        Emoticon.fromCodePoints(0x1f5d2, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5d3, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4c7),
        Emoticon.fromCodePoints(0x1f4c8),
        Emoticon.fromCodePoints(0x1f4c9),
        Emoticon.fromCodePoints(0x1f4ca),
        Emoticon.fromCodePoints(0x1f4cb),
        Emoticon.fromCodePoints(0x1f4cc),
        Emoticon.fromCodePoints(0x1f4cd),
        Emoticon.fromCodePoints(0x1f4ce),
        Emoticon.fromCodePoints(0x1f587, 0xfe0f),
        Emoticon.fromCodePoints(0x1f4cf),
        Emoticon.fromCodePoints(0x1f4d0),
        Emoticon.fromCodePoints(0x2702, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5c3, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5c4, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5d1, 0xfe0f),
        Emoticon.fromCodePoints(0x1f512),
        Emoticon.fromCodePoints(0x1f513),
        Emoticon.fromCodePoints(0x1f50f),
        Emoticon.fromCodePoints(0x1f510),
        Emoticon.fromCodePoints(0x1f511),
        Emoticon.fromCodePoints(0x1f5dd, 0xfe0f),
        Emoticon.fromCodePoints(0x1f528),
        // Emoticon.fromCodePoints(0x1fa93),
        Emoticon.fromCodePoints(0x26cf, 0xfe0f),
        Emoticon.fromCodePoints(0x2692, 0xfe0f),
        Emoticon.fromCodePoints(0x1f6e0, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5e1, 0xfe0f),
        Emoticon.fromCodePoints(0x2694, 0xfe0f),
        Emoticon.fromCodePoints(0x1f52b),
        Emoticon.fromCodePoints(0x1f3f9),
        Emoticon.fromCodePoints(0x1f6e1, 0xfe0f),
        Emoticon.fromCodePoints(0x1f527),
        Emoticon.fromCodePoints(0x1f529),
        Emoticon.fromCodePoints(0x2699, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5dc, 0xfe0f),
        Emoticon.fromCodePoints(0x2696, 0xfe0f),
        Emoticon.fromCodePoints(0x1f9af),
        Emoticon.fromCodePoints(0x1f517),
        Emoticon.fromCodePoints(0x26d3, 0xfe0f),
        Emoticon.fromCodePoints(0x1f9f0),
        Emoticon.fromCodePoints(0x1f9f2),
        Emoticon.fromCodePoints(0x2697, 0xfe0f),
        Emoticon.fromCodePoints(0x1f9ea),
        Emoticon.fromCodePoints(0x1f9eb),
        Emoticon.fromCodePoints(0x1f9ec),
        Emoticon.fromCodePoints(0x1f52c),
        Emoticon.fromCodePoints(0x1f52d),
        Emoticon.fromCodePoints(0x1f4e1),
        Emoticon.fromCodePoints(0x1f489),
        // Emoticon.fromCodePoints(0x1fa78),
        Emoticon.fromCodePoints(0x1f48a),
        // Emoticon.fromCodePoints(0x1fa79),
        // Emoticon.fromCodePoints(0x1fa7a),
        Emoticon.fromCodePoints(0x1f6aa),
        Emoticon.fromCodePoints(0x1f6cf, 0xfe0f),
        Emoticon.fromCodePoints(0x1f6cb, 0xfe0f),
        // Emoticon.fromCodePoints(0x1fa91),
        Emoticon.fromCodePoints(0x1f6bd),
        Emoticon.fromCodePoints(0x1f6bf),
        Emoticon.fromCodePoints(0x1f6c1),
        // Emoticon.fromCodePoints(0x1fa92),
        Emoticon.fromCodePoints(0x1f9f4),
        Emoticon.fromCodePoints(0x1f9f7),
        Emoticon.fromCodePoints(0x1f9f9),
        Emoticon.fromCodePoints(0x1f9fa),
        Emoticon.fromCodePoints(0x1f9fb),
        Emoticon.fromCodePoints(0x1f9fc),
        Emoticon.fromCodePoints(0x1f9fd),
        Emoticon.fromCodePoints(0x1f9ef),
        Emoticon.fromCodePoints(0x1f6d2),
        Emoticon.fromCodePoints(0x1f6ac),
        Emoticon.fromCodePoints(0x26b0, 0xfe0f),
        Emoticon.fromCodePoints(0x26b1, 0xfe0f),
        Emoticon.fromCodePoints(0x1f5ff)
    };
}
