language: android
sudo: required
dist: trusty
group: deprecated-2017Q4

android:
  components:
    - tools
    - build-tools-26.0.0
    - android-26
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x gradlew
  - git submodule update --init --recursive
script:
  
- ./gradlew build check

# Emulator Management: Create, Start and Wait
#before_script:
#  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -c 100M
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

#  gradle build connectedCheck

# https://docs.travis-ci.com/user/languages/android/