
package com.custom.keyboard.emojicon.emoji;

public class FoodAndDrink {
    public static final Emojicon[] DATA = new Emojicon[] {
        Emojicon.fromCodePoint(0x1f347),// new String[]{"grapes"}, 6, 31, false),
        Emojicon.fromCodePoint(0x1f348),// new String[]{"melon"}, 6, 32, false),
        Emojicon.fromCodePoint(0x1f349),// new String[]{"watermelon"}, 6, 33, false),
        Emojicon.fromCodePoint(0x1f34a),// new String[]{"tangerine"}, 6, 34, false),
        Emojicon.fromCodePoint(0x1f34b),// new String[]{"lemon"}, 6, 35, false),
        Emojicon.fromCodePoint(0x1f34c),// new String[]{"banana"}, 6, 36, false),
        Emojicon.fromCodePoint(0x1f34d),// new String[]{"pineapple"}, 6, 37, false),
        Emojicon.fromCodePoint(0x1f96d),// new String[]{"mango"}, 42, 3, false),
        Emojicon.fromCodePoint(0x1f34e),// new String[]{"apple"}, 6, 38, false),
        Emojicon.fromCodePoint(0x1f34f),// new String[]{"green_apple"}, 6, 39, false),
        Emojicon.fromCodePoint(0x1f350),// new String[]{"pear"}, 6, 40, false),
        Emojicon.fromCodePoint(0x1f351),// new String[]{"peach"}, 6, 41, false),
        Emojicon.fromCodePoint(0x1f352),// new String[]{"cherries"}, 6, 42, false),
        Emojicon.fromCodePoint(0x1f353),// new String[]{"strawberry"}, 6, 43, false),
        Emojicon.fromCodePoint(0x1f95d),// new String[]{"kiwifruit"}, 41, 44, false),
        Emojicon.fromCodePoint(0x1f345),// new String[]{"tomato"}, 6, 29, false),
        Emojicon.fromCodePoint(0x1f965),// new String[]{"coconut"}, 41, 52, false),
        Emojicon.fromCodePoint(0x1f951),// new String[]{"avocado"}, 41, 32, false),
        Emojicon.fromCodePoint(0x1f346),// new String[]{"eggplant"}, 6, 30, false),
        Emojicon.fromCodePoint(0x1f954),// new String[]{"potato"}, 41, 35, false),
        Emojicon.fromCodePoint(0x1f955),// new String[]{"carrot"}, 41, 36, false),
        Emojicon.fromCodePoint(0x1f33d),// new String[]{"corn"}, 6, 21, false),
        Emojicon.fromCodePoints(0x1f336, 0xfe0f),// }, new String[]{"hot_pepper"}, 6, 14, false),
        Emojicon.fromCodePoint(0x1f952),// new String[]{"cucumber"}, 41, 33, false),
        Emojicon.fromCodePoint(0x1f96c),// new String[]{"leafy_green"}, 42, 2, false),
        Emojicon.fromCodePoint(0x1f966),// new String[]{"broccoli"}, 41, 53, false),
        Emojicon.fromCodePoint(0x1f9c4),// new String[]{"garlic"}, 44, 12, false),
        Emojicon.fromCodePoint(0x1f9c5),// new String[]{"onion"}, 44, 13, false),
        Emojicon.fromCodePoint(0x1f344),// new String[]{"mushroom"}, 6, 28, false),
        Emojicon.fromCodePoint(0x1f95c),// new String[]{"peanuts"}, 41, 43, false),
        Emojicon.fromCodePoint(0x1f330),// new String[]{"chestnut"}, 6, 8, false),
        Emojicon.fromCodePoint(0x1f35e),// new String[]{"bread"}, 6, 54, false),
        Emojicon.fromCodePoint(0x1f950),// new String[]{"croissant"}, 41, 31, false),
        Emojicon.fromCodePoint(0x1f956),// new String[]{"baguette_bread"}, 41, 37, false),
        Emojicon.fromCodePoint(0x1f968),// new String[]{"pretzel"}, 41, 55, false),
        Emojicon.fromCodePoint(0x1f96f),// new String[]{"bagel"}, 42, 5, false),
        Emojicon.fromCodePoint(0x1f95e),// new String[]{"pancakes"}, 41, 45, false),
        Emojicon.fromCodePoint(0x1f9c7),// new String[]{"waffle"}, 44, 15, false),
        Emojicon.fromCodePoint(0x1f9c0),// new String[]{"cheese_wedge"}, 44, 8, false),
        Emojicon.fromCodePoint(0x1f356),// new String[]{"meat_on_bone"}, 6, 46, false),
        Emojicon.fromCodePoint(0x1f357),// new String[]{"poultry_leg"}, 6, 47, false),
        Emojicon.fromCodePoint(0x1f969),// new String[]{"cut_of_meat"}, 41, 56, false),
        Emojicon.fromCodePoint(0x1f953),// new String[]{"bacon"}, 41, 34, false),
        Emojicon.fromCodePoint(0x1f354),// new String[]{"hamburger"}, 6, 44, false),
        Emojicon.fromCodePoint(0x1f35f),// new String[]{"fries"}, 6, 55, false),
        Emojicon.fromCodePoint(0x1f355),// new String[]{"pizza"}, 6, 45, false),
        Emojicon.fromCodePoint(0x1f32d),// new String[]{"hotdog"}, 6, 5, false),
        Emojicon.fromCodePoint(0x1f96a),// new String[]{"sandwich"}, 42, 0, false),
        Emojicon.fromCodePoint(0x1f32e),// new String[]{"taco"}, 6, 6, false),
        Emojicon.fromCodePoint(0x1f32f),// new String[]{"burrito"}, 6, 7, false),
        Emojicon.fromCodePoint(0x1f959),// new String[]{"stuffed_flatbread"}, 41, 40, false),
        Emojicon.fromCodePoint(0x1f9c6),// new String[]{"falafel"}, 44, 14, false),
        Emojicon.fromCodePoint(0x1f95a),// new String[]{"egg"}, 41, 41, false),
        Emojicon.fromCodePoint(0x1f373),// new String[]{"fried_egg", "cooking"}, 7, 18, false),
        Emojicon.fromCodePoint(0x1f958),// new String[]{"shallow_pan_of_food"}, 41, 39, false),
        Emojicon.fromCodePoint(0x1f372),// new String[]{"stew"}, 7, 17, false),
        Emojicon.fromCodePoint(0x1f963),// new String[]{"bowl_with_spoon"}, 41, 50, false),
        Emojicon.fromCodePoint(0x1f957),// new String[]{"green_salad"}, 41, 38, false),
        Emojicon.fromCodePoint(0x1f37f),// new String[]{"popcorn"}, 7, 30, false),
        Emojicon.fromCodePoint(0x1f9c8),// new String[]{"butter"}, 44, 16, false),
        Emojicon.fromCodePoint(0x1f9c2),// new String[]{"salt"}, 44, 10, false),
        Emojicon.fromCodePoint(0x1f96b),// new String[]{"canned_food"}, 42, 1, false),
        Emojicon.fromCodePoint(0x1f371),// new String[]{"bento"}, 7, 16, false),
        Emojicon.fromCodePoint(0x1f358),// new String[]{"rice_cracker"}, 6, 48, false),
        Emojicon.fromCodePoint(0x1f359),// new String[]{"rice_ball"}, 6, 49, false),
        Emojicon.fromCodePoint(0x1f35a),// new String[]{"rice"}, 6, 50, false),
        Emojicon.fromCodePoint(0x1f35b),// new String[]{"curry"}, 6, 51, false),
        Emojicon.fromCodePoint(0x1f35c),// new String[]{"ramen"}, 6, 52, false),
        Emojicon.fromCodePoint(0x1f35d),// new String[]{"spaghetti"}, 6, 53, false),
        Emojicon.fromCodePoint(0x1f360),// new String[]{"sweet_potato"}, 6, 56, false),
        Emojicon.fromCodePoint(0x1f362),// new String[]{"oden"}, 7, 1, false),
        Emojicon.fromCodePoint(0x1f363),// new String[]{"sushi"}, 7, 2, false),
        Emojicon.fromCodePoint(0x1f364),// new String[]{"fried_shrimp"}, 7, 3, false),
        Emojicon.fromCodePoint(0x1f365),// new String[]{"fish_cake"}, 7, 4, false),
        Emojicon.fromCodePoint(0x1f96e),// new String[]{"moon_cake"}, 42, 4, false),
        Emojicon.fromCodePoint(0x1f361),// new String[]{"dango"}, 7, 0, false),
        Emojicon.fromCodePoint(0x1f95f),// new String[]{"dumpling"}, 41, 46, false),
        Emojicon.fromCodePoint(0x1f960),// new String[]{"fortune_cookie"}, 41, 47, false),
        Emojicon.fromCodePoint(0x1f961),// new String[]{"takeout_box"}, 41, 48, false),
        Emojicon.fromCodePoint(0x1f980),// new String[]{"crab"}, 42, 18, false),
        Emojicon.fromCodePoint(0x1f99e),// new String[]{"lobster"}, 42, 48, false),
        Emojicon.fromCodePoint(0x1f990),// new String[]{"shrimp"}, 42, 34, false),
        Emojicon.fromCodePoint(0x1f991),// new String[]{"squid"}, 42, 35, false),
        Emojicon.fromCodePoint(0x1f9aa),// new String[]{"oyster"}, 43, 1, false),
        Emojicon.fromCodePoint(0x1f366),// new String[]{"icecream"}, 7, 5, false),
        Emojicon.fromCodePoint(0x1f367),// new String[]{"shaved_ice"}, 7, 6, false),
        Emojicon.fromCodePoint(0x1f368),// new String[]{"ice_cream"}, 7, 7, false),
        Emojicon.fromCodePoint(0x1f369),// new String[]{"doughnut"}, 7, 8, false),
        Emojicon.fromCodePoint(0x1f36a),// new String[]{"cookie"}, 7, 9, false),
        Emojicon.fromCodePoint(0x1f382),// new String[]{"birthday"}, 7, 33, false),
        Emojicon.fromCodePoint(0x1f370),// new String[]{"cake"}, 7, 15, false),
        Emojicon.fromCodePoint(0x1f9c1),// new String[]{"cupcake"}, 44, 9, false),
        Emojicon.fromCodePoint(0x1f967),// new String[]{"pie"}, 41, 54, false),
        Emojicon.fromCodePoint(0x1f36b),// new String[]{"chocolate_bar"}, 7, 10, false),
        Emojicon.fromCodePoint(0x1f36c),// new String[]{"candy"}, 7, 11, false),
        Emojicon.fromCodePoint(0x1f36d),// new String[]{"lollipop"}, 7, 12, false),
        Emojicon.fromCodePoint(0x1f36e),// new String[]{"custard"}, 7, 13, false),
        Emojicon.fromCodePoint(0x1f36f),// new String[]{"honey_pot"}, 7, 14, false),
        Emojicon.fromCodePoint(0x1f37c),// new String[]{"baby_bottle"}, 7, 27, false),
        Emojicon.fromCodePoint(0x1f95b),// new String[]{"glass_of_milk"}, 41, 42, false),
        Emojicon.fromCodePoint(0x2615),// new String[]{"coffee"}, 53, 0, false),
        Emojicon.fromCodePoint(0x1f375),// new String[]{"tea"}, 7, 20, false),
        Emojicon.fromCodePoint(0x1f376),// new String[]{"sake"}, 7, 21, false),
        Emojicon.fromCodePoint(0x1f37e),// new String[]{"champagne"}, 7, 29, false),
        Emojicon.fromCodePoint(0x1f377),// new String[]{"wine_glass"}, 7, 22, false),
        Emojicon.fromCodePoint(0x1f378),// new String[]{"cocktail"}, 7, 23, false),
        Emojicon.fromCodePoint(0x1f379),// new String[]{"tropical_drink"}, 7, 24, false),
        Emojicon.fromCodePoint(0x1f37a),// new String[]{"beer"}, 7, 25, false),
        Emojicon.fromCodePoint(0x1f37b),// new String[]{"beers"}, 7, 26, false),
        Emojicon.fromCodePoint(0x1f942),// new String[]{"clinking_glasses"}, 41, 18, false),
        Emojicon.fromCodePoint(0x1f943),// new String[]{"tumbler_glass"}, 41, 19, false),
        Emojicon.fromCodePoint(0x1f964),// new String[]{"cup_with_straw"}, 41, 51, false),
        Emojicon.fromCodePoint(0x1f9c3),// new String[]{"beverage_box"}, 44, 11, false),
        Emojicon.fromCodePoint(0x1f9c9),// new String[]{"mate_drink"}, 44, 17, false),
        Emojicon.fromCodePoint(0x1f9ca),// new String[]{"ice_cube"}, 44, 18, false),
        Emojicon.fromCodePoint(0x1f962),// new String[]{"chopsticks"}, 41, 49, false),
        Emojicon.fromCodePoints(0x1f37d, 0xfe0f),// }, new String[]{"knife_fork_plate"}, 7, 28, false),
        Emojicon.fromCodePoint(0x1f374), // new String[]{"fork_and_knife"}, 7, 19, false),
        Emojicon.fromCodePoint(0x1f944), // new String[]{"spoon"}, 41, 20, false),
        Emojicon.fromCodePoint(0x1f52a), // new String[]{"hocho", "knife"}, 28, 13, false),
        Emojicon.fromCodePoint(0x1f3fa), // new String[]{"amphora"}, 11, 22, false)
};
}