

package com.custom.keyboard.emojicon.emoji;
public class Nature {
    public static final Emojicon[] DATA = new Emojicon[] {

        Emojicon.fromCodePoint(0x1f435),// new String[]{"monkey_face"}, 12, 25, false),
        Emojicon.fromCodePoint(0x1f412),// new String[]{"monkey"}, 11, 46, false),
        Emojicon.fromCodePoint(0x1f98d),// new String[]{"gorilla"}, 42, 31, false),
        Emojicon.fromCodePoint(0x1f9a7),// new String[]{"orangutan"}, 42, 55, false),
        Emojicon.fromCodePoint(0x1f436),// new String[]{"dog"}, 12, 26, false),
        Emojicon.fromCodePoint(0x1f415),// new String[]{"dog2"}, 11, 50, false),
        Emojicon.fromCodePoint(0x1f9ae),// new String[]{"guide_dog"}, 43, 2, false),
        Emojicon.fromCodePoints(0x1f415, 0x200d, 0x1f9ba),// }, new String[]{"service_dog"}, 11, 49, false),
        Emojicon.fromCodePoint(0x1f429),// new String[]{"poodle"}, 12, 13, false),
        Emojicon.fromCodePoint(0x1f43a),// new String[]{"wolf"}, 12, 30, false),
        Emojicon.fromCodePoint(0x1f98a),// new String[]{"fox_face"}, 42, 28, false),
        Emojicon.fromCodePoint(0x1f99d),// new String[]{"raccoon"}, 42, 47, false),
        Emojicon.fromCodePoint(0x1f431),// new String[]{"cat"}, 12, 21, false),
        Emojicon.fromCodePoint(0x1f408),// new String[]{"cat2"}, 11, 36, false),
        Emojicon.fromCodePoint(0x1f981),// new String[]{"lion_face"}, 42, 19, false),
        Emojicon.fromCodePoint(0x1f42f),// new String[]{"tiger"}, 12, 19, false),
        Emojicon.fromCodePoint(0x1f405),// new String[]{"tiger2"}, 11, 33, false),
        Emojicon.fromCodePoint(0x1f406),// new String[]{"leopard"}, 11, 34, false),
        Emojicon.fromCodePoint(0x1f434),// new String[]{"horse"}, 12, 24, false),
        Emojicon.fromCodePoint(0x1f40e),// new String[]{"racehorse"}, 11, 42, false),
        Emojicon.fromCodePoint(0x1f984),// new String[]{"unicorn_face"}, 42, 22, false),
        Emojicon.fromCodePoint(0x1f993),// new String[]{"zebra_face"}, 42, 37, false),
        Emojicon.fromCodePoint(0x1f98c),// new String[]{"deer"}, 42, 30, false),
        Emojicon.fromCodePoint(0x1f42e),// new String[]{"cow"}, 12, 18, false),
        Emojicon.fromCodePoint(0x1f402),// new String[]{"ox"}, 11, 30, false),
        Emojicon.fromCodePoint(0x1f403),// new String[]{"water_buffalo"}, 11, 31, false),
        Emojicon.fromCodePoint(0x1f404),// new String[]{"cow2"}, 11, 32, false),
        Emojicon.fromCodePoint(0x1f437),// new String[]{"pig"}, 12, 27, false),
        Emojicon.fromCodePoint(0x1f416),// new String[]{"pig2"}, 11, 51, false),
        Emojicon.fromCodePoint(0x1f417),// new String[]{"boar"}, 11, 52, false),
        Emojicon.fromCodePoint(0x1f43d),// new String[]{"pig_nose"}, 12, 33, false),
        Emojicon.fromCodePoint(0x1f40f),// new String[]{"ram"}, 11, 43, false),
        Emojicon.fromCodePoint(0x1f411),// new String[]{"sheep"}, 11, 45, false),
        Emojicon.fromCodePoint(0x1f410),// new String[]{"goat"}, 11, 44, false),
        Emojicon.fromCodePoint(0x1f42a),// new String[]{"dromedary_camel"}, 12, 14, false),
        Emojicon.fromCodePoint(0x1f42b),// new String[]{"camel"}, 12, 15, false),
        Emojicon.fromCodePoint(0x1f999),// new String[]{"llama"}, 42, 43, false),
        Emojicon.fromCodePoint(0x1f992),// new String[]{"giraffe_face"}, 42, 36, false),
        Emojicon.fromCodePoint(0x1f418),// new String[]{"elephant"}, 11, 53, false),
        Emojicon.fromCodePoint(0x1f98f),// new String[]{"rhinoceros"}, 42, 33, false),
        Emojicon.fromCodePoint(0x1f99b),// new String[]{"hippopotamus"}, 42, 45, false),
        Emojicon.fromCodePoint(0x1f42d),// new String[]{"mouse"}, 12, 17, false),
        Emojicon.fromCodePoint(0x1f401),// new String[]{"mouse2"}, 11, 29, false),
        Emojicon.fromCodePoint(0x1f400),// new String[]{"rat"}, 11, 28, false),
        Emojicon.fromCodePoint(0x1f439),// new String[]{"hamster"}, 12, 29, false),
        Emojicon.fromCodePoint(0x1f430),// new String[]{"rabbit"}, 12, 20, false),
        Emojicon.fromCodePoint(0x1f407),// new String[]{"rabbit2"}, 11, 35, false),
        Emojicon.fromCodePoints(0x1f43f, 0xfe0f),// }, new String[]{"chipmunk"}, 12, 35, false),
        Emojicon.fromCodePoint(0x1f994),// new String[]{"hedgehog"}, 42, 38, false),
        Emojicon.fromCodePoint(0x1f987),// new String[]{"bat"}, 42, 25, false),
        Emojicon.fromCodePoint(0x1f43b),// new String[]{"bear"}, 12, 31, false),
        Emojicon.fromCodePoint(0x1f428),// new String[]{"koala"}, 12, 12, false),
        Emojicon.fromCodePoint(0x1f43c),// new String[]{"panda_face"}, 12, 32, false),
        Emojicon.fromCodePoint(0x1f9a5),// new String[]{"sloth"}, 42, 53, false),
        Emojicon.fromCodePoint(0x1f9a6),// new String[]{"otter"}, 42, 54, false),
        Emojicon.fromCodePoint(0x1f9a8),// new String[]{"skunk"}, 42, 56, false),
        Emojicon.fromCodePoint(0x1f998),// new String[]{"kangaroo"}, 42, 42, false),
        Emojicon.fromCodePoint(0x1f9a1),// new String[]{"badger"}, 42, 51, false),
        Emojicon.fromCodePoint(0x1f43e),// new String[]{"feet", "paw_prints"}, 12, 34, false),
        Emojicon.fromCodePoint(0x1f983),// new String[]{"turkey"}, 42, 21, false),
        Emojicon.fromCodePoint(0x1f414),// new String[]{"chicken"}, 11, 48, false),
        Emojicon.fromCodePoint(0x1f413),// new String[]{"rooster"}, 11, 47, false),
        Emojicon.fromCodePoint(0x1f423),// new String[]{"hatching_chick"}, 12, 7, false),
        Emojicon.fromCodePoint(0x1f424),// new String[]{"baby_chick"}, 12, 8, false),
        Emojicon.fromCodePoint(0x1f425),// new String[]{"hatched_chick"}, 12, 9, false),
        Emojicon.fromCodePoint(0x1f426),// new String[]{"bird"}, 12, 10, false),
        Emojicon.fromCodePoint(0x1f427),// new String[]{"penguin"}, 12, 11, false),
        Emojicon.fromCodePoints(0x1f54a, 0xfe0f),// }, new String[]{"dove_of_peace"}, 28, 34, false),
        Emojicon.fromCodePoint(0x1f985),// new String[]{"eagle"}, 42, 23, false),
        Emojicon.fromCodePoint(0x1f986),// new String[]{"duck"}, 42, 24, false),
        Emojicon.fromCodePoint(0x1f9a2),// new String[]{"swan"}, 42, 52, false),
        Emojicon.fromCodePoint(0x1f989),// new String[]{"owl"}, 42, 27, false),
        Emojicon.fromCodePoint(0x1f9a9),// new String[]{"flamingo"}, 43, 0, false),
        Emojicon.fromCodePoint(0x1f99a),// new String[]{"peacock"}, 42, 44, false),
        Emojicon.fromCodePoint(0x1f99c),// new String[]{"parrot"}, 42, 46, false),
        Emojicon.fromCodePoint(0x1f438),// new String[]{"frog"}, 12, 28, false),
        Emojicon.fromCodePoint(0x1f40a),// new String[]{"crocodile"}, 11, 38, false),
        Emojicon.fromCodePoint(0x1f422),// new String[]{"turtle"}, 12, 6, false),
        Emojicon.fromCodePoint(0x1f98e),// new String[]{"lizard"}, 42, 32, false),
        Emojicon.fromCodePoint(0x1f40d),// new String[]{"snake"}, 11, 41, false),
        Emojicon.fromCodePoint(0x1f432),// new String[]{"dragon_face"}, 12, 22, false),
        Emojicon.fromCodePoint(0x1f409),// new String[]{"dragon"}, 11, 37, false),
        Emojicon.fromCodePoint(0x1f995),// new String[]{"sauropod"}, 42, 39, false),
        Emojicon.fromCodePoint(0x1f996),// new String[]{"t-rex"}, 42, 40, false),
        Emojicon.fromCodePoint(0x1f433),// new String[]{"whale"}, 12, 23, false),
        Emojicon.fromCodePoint(0x1f40b),// new String[]{"whale2"}, 11, 39, false),
        Emojicon.fromCodePoint(0x1f42c),// new String[]{"dolphin", "flipper"}, 12, 16, false),
        Emojicon.fromCodePoint(0x1f41f),// new String[]{"fish"}, 12, 3, false),
        Emojicon.fromCodePoint(0x1f420),// new String[]{"tropical_fish"}, 12, 4, false),
        Emojicon.fromCodePoint(0x1f421),// new String[]{"blowfish"}, 12, 5, false),
        Emojicon.fromCodePoint(0x1f988),// new String[]{"shark"}, 42, 26, false),
        Emojicon.fromCodePoint(0x1f419),// new String[]{"octopus"}, 11, 54, false),
        Emojicon.fromCodePoint(0x1f41a),// new String[]{"shell"}, 11, 55, false),
        Emojicon.fromCodePoint(0x1f40c),// new String[]{"snail"}, 11, 40, false),
        Emojicon.fromCodePoint(0x1f98b),// new String[]{"butterfly"}, 42, 29, false),
        Emojicon.fromCodePoint(0x1f41b),// new String[]{"bug"}, 11, 56, false),
        Emojicon.fromCodePoint(0x1f41c),// new String[]{"ant"}, 12, 0, false),
        Emojicon.fromCodePoint(0x1f41d),// new String[]{"bee", "honeybee"}, 12, 1, false),
        Emojicon.fromCodePoint(0x1f41e),// new String[]{"beetle"}, 12, 2, false),
        Emojicon.fromCodePoint(0x1f997),// new String[]{"cricket"}, 42, 41, false),
        Emojicon.fromCodePoints(0x1f577, 0xfe0f),// }, new String[]{"spider"}, 29, 34, false),
        Emojicon.fromCodePoints(0x1f578, 0xfe0f),// }, new String[]{"spider_web"}, 29, 35, false),
        Emojicon.fromCodePoint(0x1f982),// new String[]{"scorpion"}, 42, 20, false),
        Emojicon.fromCodePoint(0x1f99f),// new String[]{"mosquito"}, 42, 49, false),
        Emojicon.fromCodePoint(0x1f9a0),// new String[]{"microbe"}, 42, 50, false),
        Emojicon.fromCodePoint(0x1f490),// new String[]{"bouquet"}, 25, 26, false),
        Emojicon.fromCodePoint(0x1f338),// new String[]{"cherry_blossom"}, 6, 16, false),
        Emojicon.fromCodePoint(0x1f4ae),// new String[]{"white_flower"}, 26, 4, false),
        Emojicon.fromCodePoints(0x1f3f5, 0xfe0f),// }, new String[]{"rosette"}, 11, 18, false),
        Emojicon.fromCodePoint(0x1f339),// new String[]{"rose"}, 6, 17, false),
        Emojicon.fromCodePoint(0x1f940),// new String[]{"wilted_flower"}, 41, 16, false),
        Emojicon.fromCodePoint(0x1f33a),// new String[]{"hibiscus"}, 6, 18, false),
        Emojicon.fromCodePoint(0x1f33b),// new String[]{"sunflower"}, 6, 19, false),
        Emojicon.fromCodePoint(0x1f33c),// new String[]{"blossom"}, 6, 20, false),
        Emojicon.fromCodePoint(0x1f337),// new String[]{"tulip"}, 6, 15, false),
        Emojicon.fromCodePoint(0x1f331),// new String[]{"seedling"}, 6, 9, false),
        Emojicon.fromCodePoint(0x1f332),// new String[]{"evergreen_tree"}, 6, 10, false),
        Emojicon.fromCodePoint(0x1f333),// new String[]{"deciduous_tree"}, 6, 11, false),
        Emojicon.fromCodePoint(0x1f334),// new String[]{"palm_tree"}, 6, 12, false),
        Emojicon.fromCodePoint(0x1f335),// new String[]{"cactus"}, 6, 13, false),
        Emojicon.fromCodePoint(0x1f33e),// new String[]{"ear_of_rice"}, 6, 22, false),
        Emojicon.fromCodePoint(0x1f33f),// new String[]{"herb"}, 6, 23, false),
        Emojicon.fromCodePoints(0x2618, 0xfe0f),// }, new String[]{"shamrock"}, 53, 1, false),
        Emojicon.fromCodePoint(0x1f340),// new String[]{"four_leaf_clover"}, 6, 24, false),
        Emojicon.fromCodePoint(0x1f341),// new String[]{"maple_leaf"}, 6, 25, false),
        Emojicon.fromCodePoint(0x1f342),// new String[]{"fallen_leaf"}, 6, 26, false),
        Emojicon.fromCodePoint(0x1f343),// new String[]{"leaves"}, 6, 27, false)
    };
}
