
package com.custom.keyboard.emojicon.emoji;
public class Objects {
    public static final Emojicon[] DATA = new Emojicon[] {
        Emojicon.fromCodePoint(0x1f453),//  new String[]{"eyeglasses"}, 14, 7, false),
        Emojicon.fromCodePoints(0x1f576, 0xfe0f),// }, new String[]{"dark_sunglasses"}, 29, 33, false),
        Emojicon.fromCodePoint(0x1f97d),//  new String[]{"goggles"}, 42, 15, false),
        Emojicon.fromCodePoint(0x1f97c),//  new String[]{"lab_coat"}, 42, 14, false),
        Emojicon.fromCodePoint(0x1f9ba),//  new String[]{"safety_vest"}, 43, 54, false),
        Emojicon.fromCodePoint(0x1f454),//  new String[]{"necktie"}, 14, 8, false),
        Emojicon.fromCodePoint(0x1f455),//  new String[]{"shirt", "tshirt"}, 14, 9, false),
        Emojicon.fromCodePoint(0x1f456),//  new String[]{"jeans"}, 14, 10, false),
        Emojicon.fromCodePoint(0x1f9e3),//  new String[]{"scarf"}, 51, 22, false),
        Emojicon.fromCodePoint(0x1f9e4),//  new String[]{"gloves"}, 51, 23, false),
        Emojicon.fromCodePoint(0x1f9e5),//  new String[]{"coat"}, 51, 24, false),
        Emojicon.fromCodePoint(0x1f9e6),//  new String[]{"socks"}, 51, 25, false),
        Emojicon.fromCodePoint(0x1f457),//  new String[]{"dress"}, 14, 11, false),
        Emojicon.fromCodePoint(0x1f458),//  new String[]{"kimono"}, 14, 12, false),
        Emojicon.fromCodePoint(0x1f97b),//  new String[]{"sari"}, 42, 13, false),
        Emojicon.fromCodePoint(0x1fa71),//  new String[]{"one-piece_swimsuit"}, 51, 52, false),
        Emojicon.fromCodePoint(0x1fa72),//  new String[]{"briefs"}, 51, 53, false),
        Emojicon.fromCodePoint(0x1fa73),//  new String[]{"shorts"}, 51, 54, false),
        Emojicon.fromCodePoint(0x1f459),//  new String[]{"bikini"}, 14, 13, false),
        Emojicon.fromCodePoint(0x1f45a),//  new String[]{"womans_clothes"}, 14, 14, false),
        Emojicon.fromCodePoint(0x1f45b),//  new String[]{"purse"}, 14, 15, false),
        Emojicon.fromCodePoint(0x1f45c),//  new String[]{"handbag"}, 14, 16, false),
        Emojicon.fromCodePoint(0x1f45d),//  new String[]{"pouch"}, 14, 17, false),
        Emojicon.fromCodePoints(0x1f6cd, 0xfe0f),// }, new String[]{"shopping_bags"}, 36, 35, false),
        Emojicon.fromCodePoint(0x1f392),//  new String[]{"school_satchel"}, 7, 54, false),
        Emojicon.fromCodePoint(0x1f45e),//  new String[]{"mans_shoe", "shoe"}, 14, 18, false),
        Emojicon.fromCodePoint(0x1f45f),//  new String[]{"athletic_shoe"}, 14, 19, false),
        Emojicon.fromCodePoint(0x1f97e),//  new String[]{"hiking_boot"}, 42, 16, false),
        Emojicon.fromCodePoint(0x1f97f),//  new String[]{"womans_flat_shoe"}, 42, 17, false),
        Emojicon.fromCodePoint(0x1f460),//  new String[]{"high_heel"}, 14, 20, false),
        Emojicon.fromCodePoint(0x1f461),//  new String[]{"sandal"}, 14, 21, false),
        Emojicon.fromCodePoint(0x1fa70),//  new String[]{"ballet_shoes"}, 51, 51, false),
        Emojicon.fromCodePoint(0x1f462),//  new String[]{"boot"}, 14, 22, false),
        Emojicon.fromCodePoint(0x1f451),//  new String[]{"crown"}, 14, 5, false),
        Emojicon.fromCodePoint(0x1f452),//  new String[]{"womans_hat"}, 14, 6, false),
        Emojicon.fromCodePoint(0x1f3a9),//  new String[]{"tophat"}, 8, 15, false),
        Emojicon.fromCodePoint(0x1f393),//  new String[]{"mortar_board"}, 7, 55, false),
        Emojicon.fromCodePoint(0x1f9e2),//  new String[]{"billed_cap"}, 51, 21, false),
        Emojicon.fromCodePoints(0x26d1, 0xfe0f),// }, new String[]{"helmet_with_white_cross"}, 54, 6, false),
        Emojicon.fromCodePoint(0x1f4ff),//  new String[]{"prayer_beads"}, 27, 27, false),
        Emojicon.fromCodePoint(0x1f484),//  new String[]{"lipstick"}, 24, 32, false),
        Emojicon.fromCodePoint(0x1f48d),//  new String[]{"ring"}, 25, 23, false),
        Emojicon.fromCodePoint(0x1f48e),//  new String[]{"gem"}, 25, 24, false),
        Emojicon.fromCodePoint(0x1f507),//  new String[]{"mute"}, 27, 35, false),
        Emojicon.fromCodePoint(0x1f508),//  new String[]{"speaker"}, 27, 36, false),
        Emojicon.fromCodePoint(0x1f509),//  new String[]{"sound"}, 27, 37, false),
        Emojicon.fromCodePoint(0x1f50a),//  new String[]{"loud_sound"}, 27, 38, false),
        Emojicon.fromCodePoint(0x1f4e2),//  new String[]{"loudspeaker"}, 26, 56, false),
        Emojicon.fromCodePoint(0x1f4e3),//  new String[]{"mega"}, 27, 0, false),
        Emojicon.fromCodePoint(0x1f4ef),//  new String[]{"postal_horn"}, 27, 12, false),
        Emojicon.fromCodePoint(0x1f514),//  new String[]{"bell"}, 27, 48, false),
        Emojicon.fromCodePoint(0x1f515),//  new String[]{"no_bell"}, 27, 49, false),
        Emojicon.fromCodePoint(0x1f3bc),//  new String[]{"musical_score"}, 8, 34, false),
        Emojicon.fromCodePoint(0x1f3b5),//  new String[]{"musical_note"}, 8, 27, false),
        Emojicon.fromCodePoint(0x1f3b6),//  new String[]{"notes"}, 8, 28, false),
        Emojicon.fromCodePoints(0x1f399, 0xfe0f),// }, new String[]{"studio_microphone"}, 8, 1, false),
        Emojicon.fromCodePoints(0x1f39a, 0xfe0f),// }, new String[]{"level_slider"}, 8, 2, false),
        Emojicon.fromCodePoints(0x1f39b, 0xfe0f),// }, new String[]{"control_knobs"}, 8, 3, false),
        Emojicon.fromCodePoint(0x1f3a4),//  new String[]{"microphone"}, 8, 10, false),
        Emojicon.fromCodePoint(0x1f3a7),//  new String[]{"headphones"}, 8, 13, false),
        Emojicon.fromCodePoint(0x1f4fb),//  new String[]{"radio"}, 27, 24, false),
        Emojicon.fromCodePoint(0x1f3b7),//  new String[]{"saxophone"}, 8, 29, false),
        Emojicon.fromCodePoint(0x1f3b8),//  new String[]{"guitar"}, 8, 30, false),
        Emojicon.fromCodePoint(0x1f3b9),//  new String[]{"musical_keyboard"}, 8, 31, false),
        Emojicon.fromCodePoint(0x1f3ba),//  new String[]{"trumpet"}, 8, 32, false),
        Emojicon.fromCodePoint(0x1f3bb),//  new String[]{"violin"}, 8, 33, false),
        Emojicon.fromCodePoint(0x1fa95),//  new String[]{"banjo"}, 52, 9, false),
        Emojicon.fromCodePoint(0x1f941),//  new String[]{"drum_with_drumsticks"}, 41, 17, false),
        Emojicon.fromCodePoint(0x1f4f1),//  new String[]{"iphone"}, 27, 14, false),
        Emojicon.fromCodePoint(0x1f4f2),//  new String[]{"calling"}, 27, 15, false),
        Emojicon.fromCodePoints(0x260e, 0xfe0f),// }, new String[]{"phone", "telephone"}, 52, 54, false),
        Emojicon.fromCodePoint(0x1f4de),//  new String[]{"telephone_receiver"}, 26, 52, false),
        Emojicon.fromCodePoint(0x1f4df),//  new String[]{"pager"}, 26, 53, false),
        Emojicon.fromCodePoint(0x1f4e0),//  new String[]{"fax"}, 26, 54, false),
        Emojicon.fromCodePoint(0x1f50b),//  new String[]{"battery"}, 27, 39, false),
        Emojicon.fromCodePoint(0x1f50c),//  new String[]{"electric_plug"}, 27, 40, false),
        Emojicon.fromCodePoint(0x1f4bb),//  new String[]{"computer"}, 26, 17, false),
        Emojicon.fromCodePoints(0x1f5a5, 0xfe0f),// }, new String[]{"desktop_computer"}, 30, 10, false),
        Emojicon.fromCodePoints(0x1f5a8, 0xfe0f),// }, new String[]{"printer"}, 30, 11, false),
        Emojicon.fromCodePoints(0x2328, 0xfe0f),// }, new String[]{"keyboard"}, 52, 24, false),
        Emojicon.fromCodePoints(0x1f5b1, 0xfe0f),// }, new String[]{"three_button_mouse"}, 30, 12, false),
        Emojicon.fromCodePoints(0x1f5b2, 0xfe0f),// }, new String[]{"trackball"}, 30, 13, false),
        Emojicon.fromCodePoint(0x1f4bd),//  new String[]{"minidisc"}, 26, 19, false),
        Emojicon.fromCodePoint(0x1f4be),//  new String[]{"floppy_disk"}, 26, 20, false),
        Emojicon.fromCodePoint(0x1f4bf),//  new String[]{"cd"}, 26, 21, false),
        Emojicon.fromCodePoint(0x1f4c0),//  new String[]{"dvd"}, 26, 22, false),
        Emojicon.fromCodePoint(0x1f9ee),//  new String[]{"abacus"}, 51, 33, false),
        Emojicon.fromCodePoint(0x1f3a5),//  new String[]{"movie_camera"}, 8, 11, false),
        Emojicon.fromCodePoints(0x1f39e, 0xfe0f),// }, new String[]{"film_frames"}, 8, 4, false),
        Emojicon.fromCodePoints(0x1f4fd, 0xfe0f),// }, new String[]{"film_projector"}, 27, 26, false),
        Emojicon.fromCodePoint(0x1f3ac),//  new String[]{"clapper"}, 8, 18, false),
        Emojicon.fromCodePoint(0x1f4fa),//  new String[]{"tv"}, 27, 23, false),
        Emojicon.fromCodePoint(0x1f4f7),//  new String[]{"camera"}, 27, 20, false),
        Emojicon.fromCodePoint(0x1f4f8),//  new String[]{"camera_with_flash"}, 27, 21, false),
        Emojicon.fromCodePoint(0x1f4f9),//  new String[]{"video_camera"}, 27, 22, false),
        Emojicon.fromCodePoint(0x1f4fc),//  new String[]{"vhs"}, 27, 25, false),
        Emojicon.fromCodePoint(0x1f50d),//  new String[]{"mag"}, 27, 41, false),
        Emojicon.fromCodePoint(0x1f50e),//  new String[]{"mag_right"}, 27, 42, false),
        Emojicon.fromCodePoints(0x1f56f, 0xfe0f),// }, new String[]{"candle"}, 29, 6, false),
        Emojicon.fromCodePoint(0x1f4a1),//  new String[]{"bulb"}, 25, 43, false),
        Emojicon.fromCodePoint(0x1f526),//  new String[]{"flashlight"}, 28, 9, false),
        Emojicon.fromCodePoint(0x1f3ee),//  new String[]{"izakaya_lantern", "lantern"}, 11, 8, false),
        Emojicon.fromCodePoint(0x1fa94),//  new String[]{"diya_lamp"}, 52, 8, false),
        Emojicon.fromCodePoint(0x1f4d4),//  new String[]{"notebook_with_decorative_cover"}, 26, 42, false),
        Emojicon.fromCodePoint(0x1f4d5),//  new String[]{"closed_book"}, 26, 43, false),
        Emojicon.fromCodePoint(0x1f4d6),//  new String[]{"book", "open_book"}, 26, 44, false),
        Emojicon.fromCodePoint(0x1f4d7),//  new String[]{"green_book"}, 26, 45, false),
        Emojicon.fromCodePoint(0x1f4d8),//  new String[]{"blue_book"}, 26, 46, false),
        Emojicon.fromCodePoint(0x1f4d9),//  new String[]{"orange_book"}, 26, 47, false),
        Emojicon.fromCodePoint(0x1f4da),//  new String[]{"books"}, 26, 48, false),
        Emojicon.fromCodePoint(0x1f4d3),//  new String[]{"notebook"}, 26, 41, false),
        Emojicon.fromCodePoint(0x1f4d2),//  new String[]{"ledger"}, 26, 40, false),
        Emojicon.fromCodePoint(0x1f4c3),//  new String[]{"page_with_curl"}, 26, 25, false),
        Emojicon.fromCodePoint(0x1f4dc),//  new String[]{"scroll"}, 26, 50, false),
        Emojicon.fromCodePoint(0x1f4c4),//  new String[]{"page_facing_up"}, 26, 26, false),
        Emojicon.fromCodePoint(0x1f4f0),//  new String[]{"newspaper"}, 27, 13, false),
        Emojicon.fromCodePoints(0x1f5de, 0xfe0f),// }, new String[]{"rolled_up_newspaper"}, 30, 23, false),
        Emojicon.fromCodePoint(0x1f4d1),//  new String[]{"bookmark_tabs"}, 26, 39, false),
        Emojicon.fromCodePoint(0x1f516),//  new String[]{"bookmark"}, 27, 50, false),
        Emojicon.fromCodePoints(0x1f3f7, 0xfe0f),// }, new String[]{"label"}, 11, 19, false),
        Emojicon.fromCodePoint(0x1f4b0),//  new String[]{"moneybag"}, 26, 6, false),
        Emojicon.fromCodePoint(0x1f4b4),//  new String[]{"yen"}, 26, 10, false),
        Emojicon.fromCodePoint(0x1f4b5),//  new String[]{"dollar"}, 26, 11, false),
        Emojicon.fromCodePoint(0x1f4b6),//  new String[]{"euro"}, 26, 12, false),
        Emojicon.fromCodePoint(0x1f4b7),//  new String[]{"pound"}, 26, 13, false),
        Emojicon.fromCodePoint(0x1f4b8),//  new String[]{"money_with_wings"}, 26, 14, false),
        Emojicon.fromCodePoint(0x1f4b3),//  new String[]{"credit_card"}, 26, 9, false),
        Emojicon.fromCodePoint(0x1f9fe),//  new String[]{"receipt"}, 51, 49, false),
        Emojicon.fromCodePoint(0x1f4b9),//  new String[]{"chart"}, 26, 15, false),
        Emojicon.fromCodePoint(0x1f4b1),//  new String[]{"currency_exchange"}, 26, 7, false),
        Emojicon.fromCodePoint(0x1f4b2),//  new String[]{"heavy_dollar_sign"}, 26, 8, false),
        Emojicon.fromCodePoints(0x2709, 0xfe0f),// }, new String[]{"email", "envelope"}, 54, 42, false),
        Emojicon.fromCodePoint(0x1f4e7),//  new String[]{"e-mail"}, 27, 4, false),
        Emojicon.fromCodePoint(0x1f4e8),//  new String[]{"incoming_envelope"}, 27, 5, false),
        Emojicon.fromCodePoint(0x1f4e9),//  new String[]{"envelope_with_arrow"}, 27, 6, false),
        Emojicon.fromCodePoint(0x1f4e4),//  new String[]{"outbox_tray"}, 27, 1, false),
        Emojicon.fromCodePoint(0x1f4e5),//  new String[]{"inbox_tray"}, 27, 2, false),
        Emojicon.fromCodePoint(0x1f4e6),//  new String[]{"package"}, 27, 3, false),
        Emojicon.fromCodePoint(0x1f4eb),//  new String[]{"mailbox"}, 27, 8, false),
        Emojicon.fromCodePoint(0x1f4ea),//  new String[]{"mailbox_closed"}, 27, 7, false),
        Emojicon.fromCodePoint(0x1f4ec),//  new String[]{"mailbox_with_mail"}, 27, 9, false),
        Emojicon.fromCodePoint(0x1f4ed),//  new String[]{"mailbox_with_no_mail"}, 27, 10, false),
        Emojicon.fromCodePoint(0x1f4ee),//  new String[]{"postbox"}, 27, 11, false),
        Emojicon.fromCodePoints(0x1f5f3, 0xfe0f),// }, new String[]{"ballot_box_with_ballot"}, 30, 28, false),
        Emojicon.fromCodePoints(0x270f, 0xfe0f),// }, new String[]{"pencil2"}, 55, 10, false),
        Emojicon.fromCodePoints(0x2712, 0xfe0f),// }, new String[]{"black_nib"}, 55, 11, false),
        Emojicon.fromCodePoints(0x1f58b, 0xfe0f),// }, new String[]{"lower_left_fountain_pen"}, 29, 45, false),
        Emojicon.fromCodePoints(0x1f58a, 0xfe0f),// }, new String[]{"lower_left_ballpoint_pen"}, 29, 44, false),
        Emojicon.fromCodePoints(0x1f58c, 0xfe0f),// }, new String[]{"lower_left_paintbrush"}, 29, 46, false),
        Emojicon.fromCodePoints(0x1f58d, 0xfe0f),// }, new String[]{"lower_left_crayon"}, 29, 47, false),
        Emojicon.fromCodePoint(0x1f4dd),//  new String[]{"memo", "pencil"}, 26, 51, false),
        Emojicon.fromCodePoint(0x1f4bc),//  new String[]{"briefcase"}, 26, 18, false),
        Emojicon.fromCodePoint(0x1f4c1),//  new String[]{"file_folder"}, 26, 23, false),
        Emojicon.fromCodePoint(0x1f4c2),//  new String[]{"open_file_folder"}, 26, 24, false),
        Emojicon.fromCodePoints(0x1f5c2, 0xfe0f),// }, new String[]{"card_index_dividers"}, 30, 15, false),
        Emojicon.fromCodePoint(0x1f4c5),//  new String[]{"date"}, 26, 27, false),
        Emojicon.fromCodePoint(0x1f4c6),//  new String[]{"calendar"}, 26, 28, false),
        Emojicon.fromCodePoints(0x1f5d2, 0xfe0f),// }, new String[]{"spiral_note_pad"}, 30, 19, false),
        Emojicon.fromCodePoints(0x1f5d3, 0xfe0f),// }, new String[]{"spiral_calendar_pad"}, 30, 20, false),
        Emojicon.fromCodePoint(0x1f4c7),//  new String[]{"card_index"}, 26, 29, false),
        Emojicon.fromCodePoint(0x1f4c8),//  new String[]{"chart_with_upwards_trend"}, 26, 30, false),
        Emojicon.fromCodePoint(0x1f4c9),//  new String[]{"chart_with_downwards_trend"}, 26, 31, false),
        Emojicon.fromCodePoint(0x1f4ca),//  new String[]{"bar_chart"}, 26, 32, false),
        Emojicon.fromCodePoint(0x1f4cb),//  new String[]{"clipboard"}, 26, 33, false),
        Emojicon.fromCodePoint(0x1f4cc),//  new String[]{"pushpin"}, 26, 34, false),
        Emojicon.fromCodePoint(0x1f4cd),//  new String[]{"round_pushpin"}, 26, 35, false),
        Emojicon.fromCodePoint(0x1f4ce),//  new String[]{"paperclip"}, 26, 36, false),
        Emojicon.fromCodePoints(0x1f587, 0xfe0f),// }, new String[]{"linked_paperclips"}, 29, 43, false),
        Emojicon.fromCodePoint(0x1f4cf),//  new String[]{"straight_ruler"}, 26, 37, false),
        Emojicon.fromCodePoint(0x1f4d0),//  new String[]{"triangular_ruler"}, 26, 38, false),
        Emojicon.fromCodePoints(0x2702, 0xfe0f),// }, new String[]{"scissors"}, 54, 39, false),
        Emojicon.fromCodePoints(0x1f5c3, 0xfe0f),// }, new String[]{"card_file_box"}, 30, 16, false),
        Emojicon.fromCodePoints(0x1f5c4, 0xfe0f),// }, new String[]{"file_cabinet"}, 30, 17, false),
        Emojicon.fromCodePoints(0x1f5d1, 0xfe0f),// }, new String[]{"wastebasket"}, 30, 18, false),
        Emojicon.fromCodePoint(0x1f512),//  new String[]{"lock"}, 27, 46, false),
        Emojicon.fromCodePoint(0x1f513),//  new String[]{"unlock"}, 27, 47, false),
        Emojicon.fromCodePoint(0x1f50f),//  new String[]{"lock_with_ink_pen"}, 27, 43, false),
        Emojicon.fromCodePoint(0x1f510),//  new String[]{"closed_lock_with_key"}, 27, 44, false),
        Emojicon.fromCodePoint(0x1f511),//  new String[]{"key"}, 27, 45, false),
        Emojicon.fromCodePoints(0x1f5dd, 0xfe0f),// }, new String[]{"old_key"}, 30, 22, false),
        Emojicon.fromCodePoint(0x1f528),//  new String[]{"hammer"}, 28, 11, false),
        Emojicon.fromCodePoint(0x1fa93),//  new String[]{"axe"}, 52, 7, false),
        Emojicon.fromCodePoints(0x26cf, 0xfe0f),// }, new String[]{"pick"}, 54, 5, false),
        Emojicon.fromCodePoints(0x2692, 0xfe0f),// }, new String[]{"hammer_and_pick"}, 53, 41, false),
        Emojicon.fromCodePoints(0x1f6e0, 0xfe0f),// }, new String[]{"hammer_and_wrench"}, 36, 42, false),
        Emojicon.fromCodePoints(0x1f5e1, 0xfe0f),// }, new String[]{"dagger_knife"}, 30, 24, false),
        Emojicon.fromCodePoints(0x2694, 0xfe0f),// }, new String[]{"crossed_swords"}, 53, 43, false),
        Emojicon.fromCodePoint(0x1f52b),//  new String[]{"gun"}, 28, 14, false),
        Emojicon.fromCodePoint(0x1f3f9),//  new String[]{"bow_and_arrow"}, 11, 21, false),
        Emojicon.fromCodePoints(0x1f6e1, 0xfe0f),// }, new String[]{"shield"}, 36, 43, false),
        Emojicon.fromCodePoint(0x1f527),//  new String[]{"wrench"}, 28, 10, false),
        Emojicon.fromCodePoint(0x1f529),//  new String[]{"nut_and_bolt"}, 28, 12, false),
        Emojicon.fromCodePoints(0x2699, 0xfe0f),// }, new String[]{"gear"}, 53, 47, false),
        Emojicon.fromCodePoints(0x1f5dc, 0xfe0f),// }, new String[]{"compression"}, 30, 21, false),
        Emojicon.fromCodePoints(0x2696, 0xfe0f),// }, new String[]{"scales"}, 53, 45, false),
        Emojicon.fromCodePoint(0x1f9af),//  new String[]{"probing_cane"}, 43, 3, false),
        Emojicon.fromCodePoint(0x1f517),//  new String[]{"link"}, 27, 51, false),
        Emojicon.fromCodePoints(0x26d3, 0xfe0f),// }, new String[]{"chains"}, 54, 7, false),
        Emojicon.fromCodePoint(0x1f9f0),//  new String[]{"toolbox"}, 51, 35, false),
        Emojicon.fromCodePoint(0x1f9f2),//  new String[]{"magnet"}, 51, 37, false),
        Emojicon.fromCodePoints(0x2697, 0xfe0f),// }, new String[]{"alembic"}, 53, 46, false),
        Emojicon.fromCodePoint(0x1f9ea),//  new String[]{"test_tube"}, 51, 29, false),
        Emojicon.fromCodePoint(0x1f9eb),//  new String[]{"petri_dish"}, 51, 30, false),
        Emojicon.fromCodePoint(0x1f9ec),//  new String[]{"dna"}, 51, 31, false),
        Emojicon.fromCodePoint(0x1f52c),//  new String[]{"microscope"}, 28, 15, false),
        Emojicon.fromCodePoint(0x1f52d),//  new String[]{"telescope"}, 28, 16, false),
        Emojicon.fromCodePoint(0x1f4e1),//  new String[]{"satellite_antenna"}, 26, 55, false),
        Emojicon.fromCodePoint(0x1f489),//  new String[]{"syringe"}, 25, 19, false),
        Emojicon.fromCodePoint(0x1fa78),//  new String[]{"drop_of_blood"}, 51, 55, false),
        Emojicon.fromCodePoint(0x1f48a),//  new String[]{"pill"}, 25, 20, false),
        Emojicon.fromCodePoint(0x1fa79),//  new String[]{"adhesive_bandage"}, 51, 56, false),
        Emojicon.fromCodePoint(0x1fa7a),//  new String[]{"stethoscope"}, 52, 0, false),
        Emojicon.fromCodePoint(0x1f6aa),//  new String[]{"door"}, 35, 1, false),
        Emojicon.fromCodePoints(0x1f6cf, 0xfe0f),// }, new String[]{"bed"}, 36, 37, false),
        Emojicon.fromCodePoints(0x1f6cb, 0xfe0f),// }, new String[]{"couch_and_lamp"}, 36, 28, false),
        Emojicon.fromCodePoint(0x1fa91),//  new String[]{"chair"}, 52, 5, false),
        Emojicon.fromCodePoint(0x1f6bd),//  new String[]{"toilet"}, 36, 14, false),
        Emojicon.fromCodePoint(0x1f6bf),//  new String[]{"shower"}, 36, 16, false),
        Emojicon.fromCodePoint(0x1f6c1),//  new String[]{"bathtub"}, 36, 23, false),
        Emojicon.fromCodePoint(0x1fa92),//  new String[]{"razor"}, 52, 6, false),
        Emojicon.fromCodePoint(0x1f9f4),//  new String[]{"lotion_bottle"}, 51, 39, false),
        Emojicon.fromCodePoint(0x1f9f7),//  new String[]{"safety_pin"}, 51, 42, false),
        Emojicon.fromCodePoint(0x1f9f9),//  new String[]{"broom"}, 51, 44, false),
        Emojicon.fromCodePoint(0x1f9fa),//  new String[]{"basket"}, 51, 45, false),
        Emojicon.fromCodePoint(0x1f9fb),//  new String[]{"roll_of_paper"}, 51, 46, false),
        Emojicon.fromCodePoint(0x1f9fc),//  new String[]{"soap"}, 51, 47, false),
        Emojicon.fromCodePoint(0x1f9fd),//  new String[]{"sponge"}, 51, 48, false),
        Emojicon.fromCodePoint(0x1f9ef),//  new String[]{"fire_extinguisher"}, 51, 34, false),
        Emojicon.fromCodePoint(0x1f6d2),//  new String[]{"shopping_trolley"}, 36, 40, false),
        Emojicon.fromCodePoint(0x1f6ac),//  new String[]{"smoking"}, 35, 3, false),
        Emojicon.fromCodePoints(0x26b0, 0xfe0f),// }, new String[]{"coffin"}, 53, 54, false),
        Emojicon.fromCodePoints(0x26b1, 0xfe0f),// }, new String[]{"funeral_urn"}, 53, 55, false),
        Emojicon.fromCodePoint(0x1f5ff),//  new String[]{"moyai"}, 30, 34, false)
    };
}