
package com.custom.keyboard.emojicon.emoji;
public class Places {
    public static final Emojicon[] DATA = new Emojicon[] {

        Emojicon.fromCodePoint(0x1f30d),// new String[]{"earth_africa"}, 5, 32, false),
        Emojicon.fromCodePoint(0x1f30e),// new String[]{"earth_americas"}, 5, 33, false),
        Emojicon.fromCodePoint(0x1f30f),// new String[]{"earth_asia"}, 5, 34, false),
        Emojicon.fromCodePoint(0x1f310),// new String[]{"globe_with_meridians"}, 5, 35, false),
        Emojicon.fromCodePoints(0x1f5fa, 0xfe0f),//), // }, new String[]{"world_map"}, 30, 29, false),
        Emojicon.fromCodePoint(0x1f5fe),// new String[]{"japan"}, 30, 33, false),
        Emojicon.fromCodePoint(0x1f9ed),// new String[]{"compass"}, 51, 32, false),
        Emojicon.fromCodePoints(0x1f3d4, 0xfe0f),//), // }, new String[]{"snow_capped_mountain"}, 10, 39, false),
        Emojicon.fromCodePoints(0x26f0, 0xfe0f),//), // }, new String[]{"mountain"}, 54, 11, false),
        Emojicon.fromCodePoint(0x1f30b),// new String[]{"volcano"}, 5, 30, false),
        Emojicon.fromCodePoint(0x1f5fb),// new String[]{"mount_fuji"}, 30, 30, false),
        Emojicon.fromCodePoints(0x1f3d5, 0xfe0f),//), // }, new String[]{"camping"}, 10, 40, false),
        Emojicon.fromCodePoints(0x1f3d6, 0xfe0f),//), // }, new String[]{"beach_with_umbrella"}, 10, 41, false),
        Emojicon.fromCodePoints(0x1f3dc, 0xfe0f),//), // }, new String[]{"desert"}, 10, 47, false),
        Emojicon.fromCodePoints(0x1f3dd, 0xfe0f),//), // }, new String[]{"desert_island"}, 10, 48, false),
        Emojicon.fromCodePoints(0x1f3de, 0xfe0f),//), // }, new String[]{"national_park"}, 10, 49, false),
        Emojicon.fromCodePoints(0x1f3df, 0xfe0f),//), // }, new String[]{"stadium"}, 10, 50, false),
        Emojicon.fromCodePoints(0x1f3db, 0xfe0f),//), // }, new String[]{"classical_building"}, 10, 46, false),
        Emojicon.fromCodePoints(0x1f3d7, 0xfe0f),//), // }, new String[]{"building_construction"}, 10, 42, false),
        Emojicon.fromCodePoint(0x1f9f1),// new String[]{"bricks"}, 51, 36, false),
        Emojicon.fromCodePoints(0x1f3d8, 0xfe0f),//), // }, new String[]{"house_buildings"}, 10, 43, false),
        Emojicon.fromCodePoints(0x1f3da, 0xfe0f),//), // }, new String[]{"derelict_house_building"}, 10, 45, false),
        Emojicon.fromCodePoint(0x1f3e0),// new String[]{"house"}, 10, 51, false),
        Emojicon.fromCodePoint(0x1f3e1),// new String[]{"house_with_garden"}, 10, 52, false),
        Emojicon.fromCodePoint(0x1f3e2),// new String[]{"office"}, 10, 53, false),
        Emojicon.fromCodePoint(0x1f3e3),// new String[]{"post_office"}, 10, 54, false),
        Emojicon.fromCodePoint(0x1f3e4),// new String[]{"european_post_office"}, 10, 55, false),
        Emojicon.fromCodePoint(0x1f3e5),// new String[]{"hospital"}, 10, 56, false),
        Emojicon.fromCodePoint(0x1f3e6),// new String[]{"bank"}, 11, 0, false),
        Emojicon.fromCodePoint(0x1f3e8),// new String[]{"hotel"}, 11, 2, false),
        Emojicon.fromCodePoint(0x1f3e9),// new String[]{"love_hotel"}, 11, 3, false),
        Emojicon.fromCodePoint(0x1f3ea),// new String[]{"convenience_store"}, 11, 4, false),
        Emojicon.fromCodePoint(0x1f3eb),// new String[]{"school"}, 11, 5, false),
        Emojicon.fromCodePoint(0x1f3ec),// new String[]{"department_store"}, 11, 6, false),
        Emojicon.fromCodePoint(0x1f3ed),// new String[]{"factory"}, 11, 7, false),
        Emojicon.fromCodePoint(0x1f3ef),// new String[]{"japanese_castle"}, 11, 9, false),
        Emojicon.fromCodePoint(0x1f3f0),// new String[]{"european_castle"}, 11, 10, false),
        Emojicon.fromCodePoint(0x1f492),// new String[]{"wedding"}, 25, 28, false),
        Emojicon.fromCodePoint(0x1f5fc),// new String[]{"tokyo_tower"}, 30, 31, false),
        Emojicon.fromCodePoint(0x1f5fd),// new String[]{"statue_of_liberty"}, 30, 32, false),
        Emojicon.fromCodePoint(0x26ea),// new String[]{"church"}, 54, 10, false),
        Emojicon.fromCodePoint(0x1f54c),// new String[]{"mosque"}, 28, 36, false),
        Emojicon.fromCodePoint(0x1f6d5),// new String[]{"hindu_temple"}, 36, 41, false),
        Emojicon.fromCodePoint(0x1f54d),// new String[]{"synagogue"}, 28, 37, false),
        Emojicon.fromCodePoints(0x26e9, 0xfe0f),//), // }, new String[]{"shinto_shrine"}, 54, 9, false),
        Emojicon.fromCodePoint(0x1f54b),// new String[]{"kaaba"}, 28, 35, false),
        Emojicon.fromCodePoint(0x26f2),// new String[]{"fountain"}, 54, 13, false),
        Emojicon.fromCodePoint(0x26fa),// new String[]{"tent"}, 54, 37, false),
        Emojicon.fromCodePoint(0x1f301),// new String[]{"foggy"}, 5, 20, false),
        Emojicon.fromCodePoint(0x1f303),// new String[]{"night_with_stars"}, 5, 22, false),
        Emojicon.fromCodePoints(0x1f3d9, 0xfe0f),//), // }, new String[]{"cityscape"}, 10, 44, false),
        Emojicon.fromCodePoint(0x1f304),// new String[]{"sunrise_over_mountains"}, 5, 23, false),
        Emojicon.fromCodePoint(0x1f305),// new String[]{"sunrise"}, 5, 24, false),
        Emojicon.fromCodePoint(0x1f306),// new String[]{"city_sunset"}, 5, 25, false),
        Emojicon.fromCodePoint(0x1f307),// new String[]{"city_sunrise"}, 5, 26, false),
        Emojicon.fromCodePoint(0x1f309),// new String[]{"bridge_at_night"}, 5, 28, false),
        Emojicon.fromCodePoints(0x2668, 0xfe0f),//), // }, new String[]{"hotsprings"}, 53, 37, false),
        Emojicon.fromCodePoint(0x1f3a0),// new String[]{"carousel_horse"}, 8, 6, false),
        Emojicon.fromCodePoint(0x1f3a1),// new String[]{"ferris_wheel"}, 8, 7, false),
        Emojicon.fromCodePoint(0x1f3a2),// new String[]{"roller_coaster"}, 8, 8, false),
        Emojicon.fromCodePoint(0x1f488),// new String[]{"barber"}, 25, 18, false),
        Emojicon.fromCodePoint(0x1f3aa),// new String[]{"circus_tent"}, 8, 16, false),
        Emojicon.fromCodePoint(0x1f682),// new String[]{"steam_locomotive"}, 34, 1, false),
        Emojicon.fromCodePoint(0x1f683),// new String[]{"railway_car"}, 34, 2, false),
        Emojicon.fromCodePoint(0x1f684),// new String[]{"bullettrain_side"}, 34, 3, false),
        Emojicon.fromCodePoint(0x1f685),// new String[]{"bullettrain_front"}, 34, 4, false),
        Emojicon.fromCodePoint(0x1f686),// new String[]{"train2"}, 34, 5, false),
        Emojicon.fromCodePoint(0x1f687),// new String[]{"metro"}, 34, 6, false),
        Emojicon.fromCodePoint(0x1f688),// new String[]{"light_rail"}, 34, 7, false),
        Emojicon.fromCodePoint(0x1f689),// new String[]{"station"}, 34, 8, false),
        Emojicon.fromCodePoint(0x1f68a),// new String[]{"tram"}, 34, 9, false),
        Emojicon.fromCodePoint(0x1f69d),// new String[]{"monorail"}, 34, 28, false),
        Emojicon.fromCodePoint(0x1f69e),// new String[]{"mountain_railway"}, 34, 29, false),
        Emojicon.fromCodePoint(0x1f68b),// new String[]{"train"}, 34, 10, false),
        Emojicon.fromCodePoint(0x1f68c),// new String[]{"bus"}, 34, 11, false),
        Emojicon.fromCodePoint(0x1f68d),// new String[]{"oncoming_bus"}, 34, 12, false),
        Emojicon.fromCodePoint(0x1f68e),// new String[]{"trolleybus"}, 34, 13, false),
        Emojicon.fromCodePoint(0x1f690),// new String[]{"minibus"}, 34, 15, false),
        Emojicon.fromCodePoint(0x1f691),// new String[]{"ambulance"}, 34, 16, false),
        Emojicon.fromCodePoint(0x1f692),// new String[]{"fire_engine"}, 34, 17, false),
        Emojicon.fromCodePoint(0x1f693),// new String[]{"police_car"}, 34, 18, false),
        Emojicon.fromCodePoint(0x1f694),// new String[]{"oncoming_police_car"}, 34, 19, false),
        Emojicon.fromCodePoint(0x1f695),// new String[]{"taxi"}, 34, 20, false),
        Emojicon.fromCodePoint(0x1f696),// new String[]{"oncoming_taxi"}, 34, 21, false),
        Emojicon.fromCodePoint(0x1f697),// new String[]{"car", "red_car"}, 34, 22, false),
        Emojicon.fromCodePoint(0x1f698),// new String[]{"oncoming_automobile"}, 34, 23, false),
        Emojicon.fromCodePoint(0x1f699),// new String[]{"blue_car"}, 34, 24, false),
        Emojicon.fromCodePoint(0x1f69a),// new String[]{"truck"}, 34, 25, false),
        Emojicon.fromCodePoint(0x1f69b),// new String[]{"articulated_lorry"}, 34, 26, false),
        Emojicon.fromCodePoint(0x1f69c),// new String[]{"tractor"}, 34, 27, false),
        Emojicon.fromCodePoints(0x1f3ce, 0xfe0f),//), // }, new String[]{"racing_car"}, 10, 33, false),
        Emojicon.fromCodePoints(0x1f3cd, 0xfe0f),//), // }, new String[]{"racing_motorcycle"}, 10, 32, false),
        Emojicon.fromCodePoint(0x1f6f5),// new String[]{"motor_scooter"}, 36, 54, false),
        Emojicon.fromCodePoint(0x1f9bd),// new String[]{"manual_wheelchair"}, 44, 5, false),
        Emojicon.fromCodePoint(0x1f9bc),// new String[]{"motorized_wheelchair"}, 44, 4, false),
        Emojicon.fromCodePoint(0x1f6fa),// new String[]{"auto_rickshaw"}, 37, 2, false),
        Emojicon.fromCodePoint(0x1f6b2),// new String[]{"bike"}, 35, 9, false),
        Emojicon.fromCodePoint(0x1f6f4),// new String[]{"scooter"}, 36, 53, false),
        Emojicon.fromCodePoint(0x1f6f9),// new String[]{"skateboard"}, 37, 1, false),
        Emojicon.fromCodePoint(0x1f68f),// new String[]{"busstop"}, 34, 14, false),
        Emojicon.fromCodePoints(0x1f6e3, 0xfe0f),//), // }, new String[]{"motorway"}, 36, 45, false),
        Emojicon.fromCodePoints(0x1f6e4, 0xfe0f),//), // }, new String[]{"railway_track"}, 36, 46, false),
        Emojicon.fromCodePoints(0x1f6e2, 0xfe0f),//), // }, new String[]{"oil_drum"}, 36, 44, false),
        Emojicon.fromCodePoint(0x26fd),// new String[]{"fuelpump"}, 54, 38, false),
        Emojicon.fromCodePoint(0x1f6a8),// new String[]{"rotating_light"}, 34, 56, false),
        Emojicon.fromCodePoint(0x1f6a5),// new String[]{"traffic_light"}, 34, 53, false),
        Emojicon.fromCodePoint(0x1f6a6),// new String[]{"vertical_traffic_light"}, 34, 54, false),
        Emojicon.fromCodePoint(0x1f6d1),// new String[]{"octagonal_sign"}, 36, 39, false),
        Emojicon.fromCodePoint(0x1f6a7),// new String[]{"construction"}, 34, 55, false),
        Emojicon.fromCodePoint(0x2693),// new String[]{"anchor"}, 53, 42, false),
        Emojicon.fromCodePoint(0x26f5),// new String[]{"boat", "sailboat"}, 54, 16, false),
        Emojicon.fromCodePoint(0x1f6f6),// new String[]{"canoe"}, 36, 55, false),
        Emojicon.fromCodePoint(0x1f6a4),// new String[]{"speedboat"}, 34, 52, false),
        Emojicon.fromCodePoints(0x1f6f3, 0xfe0f),//), // }, new String[]{"passenger_ship"}, 36, 52, false),
        Emojicon.fromCodePoints(0x26f4, 0xfe0f),//), // }, new String[]{"ferry"}, 54, 15, false),
        Emojicon.fromCodePoints(0x1f6e5, 0xfe0f),//), // }, new String[]{"motor_boat"}, 36, 47, false),
        Emojicon.fromCodePoint(0x1f6a2),// new String[]{"ship"}, 34, 33, false),
        Emojicon.fromCodePoints(0x2708, 0xfe0f),//), // }, new String[]{"airplane"}, 54, 41, false),
        Emojicon.fromCodePoints(0x1f6e9, 0xfe0f),//), // }, new String[]{"small_airplane"}, 36, 48, false),
        Emojicon.fromCodePoint(0x1f6eb),// new String[]{"airplane_departure"}, 36, 49, false),
        Emojicon.fromCodePoint(0x1f6ec),// new String[]{"airplane_arriving"}, 36, 50, false),
        Emojicon.fromCodePoint(0x1fa82),// new String[]{"parachute"}, 52, 3, false),
        Emojicon.fromCodePoint(0x1f4ba),// new String[]{"seat"}, 26, 16, false),
        Emojicon.fromCodePoint(0x1f681),// new String[]{"helicopter"}, 34, 0, false),
        Emojicon.fromCodePoint(0x1f69f),// new String[]{"suspension_railway"}, 34, 30, false),
        Emojicon.fromCodePoint(0x1f6a0),// new String[]{"mountain_cableway"}, 34, 31, false),
        Emojicon.fromCodePoint(0x1f6a1),// new String[]{"aerial_tramway"}, 34, 32, false),
        Emojicon.fromCodePoints(0x1f6f0, 0xfe0f),//), // }, new String[]{"satellite"}, 36, 51, false),
        Emojicon.fromCodePoint(0x1f680),// new String[]{"rocket"}, 33, 56, false),
        Emojicon.fromCodePoint(0x1f6f8),// new String[]{"flying_saucer"}, 37, 0, false),
        Emojicon.fromCodePoints(0x1f6ce, 0xfe0f),//), // }, new String[]{"bellhop_bell"}, 36, 36, false),
        Emojicon.fromCodePoint(0x1f9f3),// new String[]{"luggage"}, 51, 38, false),
        Emojicon.fromCodePoint(0x231b),// new String[]{"hourglass"}, 52, 23, false),
        Emojicon.fromCodePoint(0x23f3),// new String[]{"hourglass_flowing_sand"}, 52, 36, false),
        Emojicon.fromCodePoint(0x231a),// new String[]{"watch"}, 52, 22, false),
        Emojicon.fromCodePoint(0x23f0),// new String[]{"alarm_clock"}, 52, 33, false),
        Emojicon.fromCodePoints(0x23f1, 0xfe0f),//), // }, new String[]{"stopwatch"}, 52, 34, false),
        Emojicon.fromCodePoints(0x23f2, 0xfe0f),//), // }, new String[]{"timer_clock"}, 52, 35, false),
        Emojicon.fromCodePoints(0x1f570, 0xfe0f),//), // }, new String[]{"mantelpiece_clock"}, 29, 7, false),
        Emojicon.fromCodePoint(0x1f55b),// new String[]{"clock12"}, 28, 50, false),
        Emojicon.fromCodePoint(0x1f567),// new String[]{"clock1230"}, 29, 5, false),
        Emojicon.fromCodePoint(0x1f550),// new String[]{"clock1"}, 28, 39, false),
        Emojicon.fromCodePoint(0x1f55c),// new String[]{"clock130"}, 28, 51, false),
        Emojicon.fromCodePoint(0x1f551),// new String[]{"clock2"}, 28, 40, false),
        Emojicon.fromCodePoint(0x1f55d),// new String[]{"clock230"}, 28, 52, false),
        Emojicon.fromCodePoint(0x1f552),// new String[]{"clock3"}, 28, 41, false),
        Emojicon.fromCodePoint(0x1f55e),// new String[]{"clock330"}, 28, 53, false),
        Emojicon.fromCodePoint(0x1f553),// new String[]{"clock4"}, 28, 42, false),
        Emojicon.fromCodePoint(0x1f55f),// new String[]{"clock430"}, 28, 54, false),
        Emojicon.fromCodePoint(0x1f554),// new String[]{"clock5"}, 28, 43, false),
        Emojicon.fromCodePoint(0x1f560),// new String[]{"clock530"}, 28, 55, false),
        Emojicon.fromCodePoint(0x1f555),// new String[]{"clock6"}, 28, 44, false),
        Emojicon.fromCodePoint(0x1f561),// new String[]{"clock630"}, 28, 56, false),
        Emojicon.fromCodePoint(0x1f556),// new String[]{"clock7"}, 28, 45, false),
        Emojicon.fromCodePoint(0x1f562),// new String[]{"clock730"}, 29, 0, false),
        Emojicon.fromCodePoint(0x1f557),// new String[]{"clock8"}, 28, 46, false),
        Emojicon.fromCodePoint(0x1f563),// new String[]{"clock830"}, 29, 1, false),
        Emojicon.fromCodePoint(0x1f558),// new String[]{"clock9"}, 28, 47, false),
        Emojicon.fromCodePoint(0x1f564),// new String[]{"clock930"}, 29, 2, false),
        Emojicon.fromCodePoint(0x1f559),// new String[]{"clock10"}, 28, 48, false),
        Emojicon.fromCodePoint(0x1f565),// new String[]{"clock1030"}, 29, 3, false),
        Emojicon.fromCodePoint(0x1f55a),// new String[]{"clock11"}, 28, 49, false),
        Emojicon.fromCodePoint(0x1f566),// new String[]{"clock1130"}, 29, 4, false),
        Emojicon.fromCodePoint(0x1f311),// new String[]{"new_moon"}, 5, 36, false),
        Emojicon.fromCodePoint(0x1f312),// new String[]{"waxing_crescent_moon"}, 5, 37, false),
        Emojicon.fromCodePoint(0x1f313),// new String[]{"first_quarter_moon"}, 5, 38, false),
        Emojicon.fromCodePoint(0x1f314),// new String[]{"moon", "waxing_gibbous_moon"}, 5, 39, false),
        Emojicon.fromCodePoint(0x1f315),// new String[]{"full_moon"}, 5, 40, false),
        Emojicon.fromCodePoint(0x1f316),// new String[]{"waning_gibbous_moon"}, 5, 41, false),
        Emojicon.fromCodePoint(0x1f317),// new String[]{"last_quarter_moon"}, 5, 42, false),
        Emojicon.fromCodePoint(0x1f318),// new String[]{"waning_crescent_moon"}, 5, 43, false),
        Emojicon.fromCodePoint(0x1f319),// new String[]{"crescent_moon"}, 5, 44, false),
        Emojicon.fromCodePoint(0x1f31a),// new String[]{"new_moon_with_face"}, 5, 45, false),
        Emojicon.fromCodePoint(0x1f31b),// new String[]{"first_quarter_moon_with_face"}, 5, 46, false),
        Emojicon.fromCodePoint(0x1f31c),// new String[]{"last_quarter_moon_with_face"}, 5, 47, false),
        Emojicon.fromCodePoints(0x1f321, 0xfe0f),//), // }, new String[]{"thermometer"}, 5, 52, false),
        Emojicon.fromCodePoints(0x2600, 0xfe0f),//), // }, new String[]{"sunny"}, 52, 49, false),
        Emojicon.fromCodePoint(0x1f31d),// new String[]{"full_moon_with_face"}, 5, 48, false),
        Emojicon.fromCodePoint(0x1f31e),// new String[]{"sun_with_face"}, 5, 49, false),
        Emojicon.fromCodePoint(0x1fa90),// new String[]{"ringed_planet"}, 52, 4, false),
        Emojicon.fromCodePoint(0x2b50),// new String[]{"star"}, 55, 42, true,
        Emojicon.fromCodePoints(0x2b50, 0xfe0f),// }, new String[0], 55, 42, true)
        // ),
        Emojicon.fromCodePoint(0x1f31f),// new String[]{"star2"}, 5, 50, false),
        Emojicon.fromCodePoint(0x1f320),// new String[]{"stars"}, 5, 51, false),
        Emojicon.fromCodePoint(0x1f30c),// new String[]{"milky_way"}, 5, 31, false),
        Emojicon.fromCodePoints(0x2601, 0xfe0f),//), // }, new String[]{"cloud"}, 52, 50, false),
        Emojicon.fromCodePoint(0x26c5),// new String[]{"partly_sunny"}, 54, 2, false),
        Emojicon.fromCodePoints(0x26c8, 0xfe0f),//), // }, new String[]{"thunder_cloud_and_rain"}, 54, 3, false),
        Emojicon.fromCodePoints(0x1f324, 0xfe0f),//), // }, new String[]{"mostly_sunny", "sun_small_cloud"}, 5, 53, false),
        Emojicon.fromCodePoints(0x1f325, 0xfe0f),//), // }, new String[]{"barely_sunny", "sun_behind_cloud"}, 5, 54, false),
        Emojicon.fromCodePoints(0x1f326, 0xfe0f),//), // }, new String[]{"partly_sunny_rain", "sun_behind_rain_cloud"}, 5, 55, false),
        Emojicon.fromCodePoints(0x1f327, 0xfe0f),//), // }, new String[]{"rain_cloud"}, 5, 56, false),
        Emojicon.fromCodePoints(0x1f328, 0xfe0f),//), // }, new String[]{"snow_cloud"}, 6, 0, false),
        Emojicon.fromCodePoints(0x1f329, 0xfe0f),//), // }, new String[]{"lightning", "lightning_cloud"}, 6, 1, false),
        Emojicon.fromCodePoints(0x1f32a, 0xfe0f),//), // }, new String[]{"tornado", "tornado_cloud"}, 6, 2, false),
        Emojicon.fromCodePoints(0x1f32b, 0xfe0f),//), // }, new String[]{"fog"}, 6, 3, false),
        Emojicon.fromCodePoints(0x1f32c, 0xfe0f),//), // }, new String[]{"wind_blowing_face"}, 6, 4, false),
        Emojicon.fromCodePoint(0x1f300),// new String[]{"cyclone"}, 5, 19, false),
        Emojicon.fromCodePoint(0x1f308),// new String[]{"rainbow"}, 5, 27, false),
        Emojicon.fromCodePoint(0x1f302),// new String[]{"closed_umbrella"}, 5, 21, false),
        Emojicon.fromCodePoints(0x2602, 0xfe0f),//), // }, new String[]{"umbrella"}, 52, 51, false),
        Emojicon.fromCodePoint(0x2614),// new String[]{"umbrella_with_rain_drops"}, 52, 56, false),
        Emojicon.fromCodePoints(0x26f1, 0xfe0f),//), // }, new String[]{"umbrella_on_ground"}, 54, 12, false),
        Emojicon.fromCodePoint(0x26a1),// new String[]{"zap"}, 53, 51, false),
        Emojicon.fromCodePoints(0x2744, 0xfe0f),//), // }, new String[]{"snowflake"}, 55, 19, false),
        Emojicon.fromCodePoints(0x2603, 0xfe0f),//), // }, new String[]{"snowman"}, 52, 52, false),
        Emojicon.fromCodePoint(0x26c4),// new String[]{"snowman_without_snow"}, 54, 1, false),
        Emojicon.fromCodePoints(0x2604, 0xfe0f),//), // }, new String[]{"comet"}, 52, 53, false),
        Emojicon.fromCodePoint(0x1f525),// new String[]{"fire"}, 28, 8, false),
        Emojicon.fromCodePoint(0x1f4a7),// new String[]{"droplet"}, 25, 49, false),
        Emojicon.fromCodePoint(0x1f30a),// new String[]{"ocean"}, 5, 29, false)

        // Emojicon.fromChars("\ud83c\uddef\ud83c\uddf5"),
        // Emojicon.fromChars("\ud83c\uddf0\ud83c\uddf7"),
        // Emojicon.fromChars("\ud83c\udde9\ud83c\uddea"),
        // Emojicon.fromChars("\ud83c\udde8\ud83c\uddf3"),
        // Emojicon.fromChars("\ud83c\uddfa\ud83c\uddf8"),
        // Emojicon.fromChars("\ud83c\uddeb\ud83c\uddf7"),
        // Emojicon.fromChars("\ud83c\uddea\ud83c\uddf8"),
        // Emojicon.fromChars("\ud83c\uddee\ud83c\uddf9"),
        // Emojicon.fromChars("\ud83c\uddf7\ud83c\uddfa"),
        // Emojicon.fromChars("\ud83c\uddec\ud83c\udde7"),
    };
}
