
package com.custom.keyboard.emojicon.emoji;
public class Symbols {
    public static final Emojicon[] DATA = new Emojicon[] {
        // Emojicon.fromChars("\u0031\u20e3"),


        Emojicon.fromCodePoint(0x1f3e7),// new String[]{"atm"}, 11, 1, false),
        Emojicon.fromCodePoint(0x1f6ae),// new String[]{"put_litter_in_its_place"}, 35, 5, false),
        Emojicon.fromCodePoint(0x1f6b0),// new String[]{"potable_water"}, 35, 7, false),
        Emojicon.fromCodePoint(0x267f),// new String[]{"wheelchair"}, 53, 40, false),
        Emojicon.fromCodePoint(0x1f6b9),// new String[]{"mens"}, 36, 10, false),
        Emojicon.fromCodePoint(0x1f6ba),// new String[]{"womens"}, 36, 11, false),
        Emojicon.fromCodePoint(0x1f6bb),// new String[]{"restroom"}, 36, 12, false),
        Emojicon.fromCodePoint(0x1f6bc),// new String[]{"baby_symbol"}, 36, 13, false),
        Emojicon.fromCodePoint(0x1f6be),// new String[]{"wc"}, 36, 15, false),
        Emojicon.fromCodePoint(0x1f6c2),// new String[]{"passport_control"}, 36, 24, false),
        Emojicon.fromCodePoint(0x1f6c3),// new String[]{"customs"}, 36, 25, false),
        Emojicon.fromCodePoint(0x1f6c4),// new String[]{"baggage_claim"}, 36, 26, false),
        Emojicon.fromCodePoint(0x1f6c5),// new String[]{"left_luggage"}, 36, 27, false),
        Emojicon.fromCodePoints(0x26a0, 0xfe0f),//), // }, new String[]{"warning"}, 53, 50, false),
        Emojicon.fromCodePoint(0x1f6b8),// new String[]{"children_crossing"}, 36, 9, false),
        Emojicon.fromCodePoint(0x26d4),// new String[]{"no_entry"}, 54, 8, false),
        Emojicon.fromCodePoint(0x1f6ab),// new String[]{"no_entry_sign"}, 35, 2, false),
        Emojicon.fromCodePoint(0x1f6b3),// new String[]{"no_bicycles"}, 35, 10, false),
        Emojicon.fromCodePoint(0x1f6ad),// new String[]{"no_smoking"}, 35, 4, false),
        Emojicon.fromCodePoint(0x1f6af),// new String[]{"do_not_litter"}, 35, 6, false),
        Emojicon.fromCodePoint(0x1f6b1),// new String[]{"non-potable_water"}, 35, 8, false),
        Emojicon.fromCodePoint(0x1f6b7),// new String[]{"no_pedestrians"}, 36, 8, false),
        Emojicon.fromCodePoint(0x1f4f5),// new String[]{"no_mobile_phones"}, 27, 18, false),
        Emojicon.fromCodePoint(0x1f51e),// new String[]{"underage"}, 28, 1, false),
        Emojicon.fromCodePoints(0x2622, 0xfe0f),//), // }, new String[]{"radioactive_sign"}, 53, 9, false),
        Emojicon.fromCodePoints(0x2623, 0xfe0f),//), // }, new String[]{"biohazard_sign"}, 53, 10, false),
        Emojicon.fromCodePoints(0x2b06, 0xfe0f),//), // }, new String[]{"arrow_up"}, 55, 38, false),
        Emojicon.fromCodePoints(0x2197, 0xfe0f),//), // }, new String[]{"arrow_upper_right"}, 52, 17, false),
        Emojicon.fromCodePoints(0x27a1, 0xfe0f),//), // }, new String[]{"arrow_right"}, 55, 32, false),
        Emojicon.fromCodePoints(0x2198, 0xfe0f),//), // }, new String[]{"arrow_lower_right"}, 52, 18, false),
        Emojicon.fromCodePoints(0x2b07, 0xfe0f),//), // }, new String[]{"arrow_down"}, 55, 39, false),
        Emojicon.fromCodePoints(0x2199, 0xfe0f),//), // }, new String[]{"arrow_lower_left"}, 52, 19, false),
        Emojicon.fromCodePoints(0x2b05, 0xfe0f),//), // }, new String[]{"arrow_left"}, 55, 37, false),
        Emojicon.fromCodePoints(0x2196, 0xfe0f),//), // }, new String[]{"arrow_upper_left"}, 52, 16, false),
        Emojicon.fromCodePoints(0x2195, 0xfe0f),//), // }, new String[]{"arrow_up_down"}, 52, 15, false),
        Emojicon.fromCodePoints(0x2194, 0xfe0f),//), // }, new String[]{"left_right_arrow"}, 52, 14, false),
        Emojicon.fromCodePoints(0x21a9, 0xfe0f),//), // }, new String[]{"leftwards_arrow_with_hook"}, 52, 20, false),
        Emojicon.fromCodePoints(0x21aa, 0xfe0f),//), // }, new String[]{"arrow_right_hook"}, 52, 21, false),
        Emojicon.fromCodePoints(0x2934, 0xfe0f),//), // }, new String[]{"arrow_heading_up"}, 55, 35, false),
        Emojicon.fromCodePoints(0x2935, 0xfe0f),//), // }, new String[]{"arrow_heading_down"}, 55, 36, false),
        Emojicon.fromCodePoint(0x1f503),// new String[]{"arrows_clockwise"}, 27, 31, false),
        Emojicon.fromCodePoint(0x1f504),// new String[]{"arrows_counterclockwise"}, 27, 32, false),
        Emojicon.fromCodePoint(0x1f519),// new String[]{"back"}, 27, 53, false),
        Emojicon.fromCodePoint(0x1f51a),// new String[]{"end"}, 27, 54, false),
        Emojicon.fromCodePoint(0x1f51b),// new String[]{"on"}, 27, 55, false),
        Emojicon.fromCodePoint(0x1f51c),// new String[]{"soon"}, 27, 56, false),
        Emojicon.fromCodePoint(0x1f51d),// new String[]{"top"}, 28, 0, false),
        Emojicon.fromCodePoint(0x1f6d0),// new String[]{"place_of_worship"}, 36, 38, false),
        Emojicon.fromCodePoints(0x269b, 0xfe0f),//), // }, new String[]{"atom_symbol"}, 53, 48, false),
        Emojicon.fromCodePoints(0x1f549, 0xfe0f),//), // }, new String[]{"om_symbol"}, 28, 33, false),
        Emojicon.fromCodePoints(0x2721, 0xfe0f),//), // }, new String[]{"star_of_david"}, 55, 15, false),
        Emojicon.fromCodePoints(0x2638, 0xfe0f),//), // }, new String[]{"wheel_of_dharma"}, 53, 15, false),
        Emojicon.fromCodePoints(0x262f, 0xfe0f),//), // }, new String[]{"yin_yang"}, 53, 14, false),
        Emojicon.fromCodePoints(0x271d, 0xfe0f),//), // }, new String[]{"latin_cross"}, 55, 14, false),
        Emojicon.fromCodePoints(0x2626, 0xfe0f),//), // }, new String[]{"orthodox_cross"}, 53, 11, false),
        Emojicon.fromCodePoints(0x262a, 0xfe0f),//), // }, new String[]{"star_and_crescent"}, 53, 12, false),
        Emojicon.fromCodePoints(0x262e, 0xfe0f),//), // }, new String[]{"peace_symbol"}, 53, 13, false),
        Emojicon.fromCodePoint(0x1f54e),// new String[]{"menorah_with_nine_branches"}, 28, 38, false),
        Emojicon.fromCodePoint(0x1f52f),// new String[]{"six_pointed_star"}, 28, 18, false),
        Emojicon.fromCodePoint(0x2648),// new String[]{"aries"}, 53, 20, false),
        Emojicon.fromCodePoint(0x2649),// new String[]{"taurus"}, 53, 21, false),
        Emojicon.fromCodePoint(0x264a),// new String[]{"gemini"}, 53, 22, false),
        Emojicon.fromCodePoint(0x264b),// new String[]{"cancer"}, 53, 23, false),
        Emojicon.fromCodePoint(0x264c),// new String[]{"leo"}, 53, 24, false),
        Emojicon.fromCodePoint(0x264d),// new String[]{"virgo"}, 53, 25, false),
        Emojicon.fromCodePoint(0x264e),// new String[]{"libra"}, 53, 26, false),
        Emojicon.fromCodePoint(0x264f),// new String[]{"scorpius"}, 53, 27, false),
        Emojicon.fromCodePoint(0x2650),// new String[]{"sagittarius"}, 53, 28, false),
        Emojicon.fromCodePoint(0x2651),// new String[]{"capricorn"}, 53, 29, false),
        Emojicon.fromCodePoint(0x2652),// new String[]{"aquarius"}, 53, 30, false),
        Emojicon.fromCodePoint(0x2653),// new String[]{"pisces"}, 53, 31, false),
        Emojicon.fromCodePoint(0x26ce),// new String[]{"ophiuchus"}, 54, 4, false),
        Emojicon.fromCodePoint(0x1f500),// new String[]{"twisted_rightwards_arrows"}, 27, 28, false),
        Emojicon.fromCodePoint(0x1f501),// new String[]{"repeat"}, 27, 29, false),
        Emojicon.fromCodePoint(0x1f502),// new String[]{"repeat_one"}, 27, 30, false),
        Emojicon.fromCodePoints(0x25b6, 0xfe0f),//), // }, new String[]{"arrow_forward"}, 52, 43, false),
        Emojicon.fromCodePoint(0x23e9),// new String[]{"fast_forward"}, 52, 26, false),
        Emojicon.fromCodePoints(0x23ed, 0xfe0f),//), // }, new String[]{"black_right_pointing_double_triangle_with_vertical_bar"}, 52, 30, false),
        Emojicon.fromCodePoints(0x23ef, 0xfe0f),//), // }, new String[]{"black_right_pointing_triangle_with_double_vertical_bar"}, 52, 32, false),
        Emojicon.fromCodePoints(0x25c0, 0xfe0f),//), // }, new String[]{"arrow_backward"}, 52, 44, false),
        Emojicon.fromCodePoint(0x23ea),// new String[]{"rewind"}, 52, 27, false),
        Emojicon.fromCodePoints(0x23ee, 0xfe0f),//), // }, new String[]{"black_left_pointing_double_triangle_with_vertical_bar"}, 52, 31, false),
        Emojicon.fromCodePoint(0x1f53c),// new String[]{"arrow_up_small"}, 28, 31, false),
        Emojicon.fromCodePoint(0x23eb),// new String[]{"arrow_double_up"}, 52, 28, false),
        Emojicon.fromCodePoint(0x1f53d),// new String[]{"arrow_down_small"}, 28, 32, false),
        Emojicon.fromCodePoint(0x23ec),// new String[]{"arrow_double_down"}, 52, 29, false),
        Emojicon.fromCodePoints(0x23f8, 0xfe0f),//), // }, new String[]{"double_vertical_bar"}, 52, 37, false),
        Emojicon.fromCodePoints(0x23f9, 0xfe0f),//), // }, new String[]{"black_square_for_stop"}, 52, 38, false),
        Emojicon.fromCodePoints(0x23fa, 0xfe0f),//), // }, new String[]{"black_circle_for_record"}, 52, 39, false),
        Emojicon.fromCodePoints(0x23cf, 0xfe0f),//), // }, new String[]{"eject"}, 52, 25, false),
        Emojicon.fromCodePoint(0x1f3a6),// new String[]{"cinema"}, 8, 12, false),
        Emojicon.fromCodePoint(0x1f505),// new String[]{"low_brightness"}, 27, 33, false),
        Emojicon.fromCodePoint(0x1f506),// new String[]{"high_brightness"}, 27, 34, false),
        Emojicon.fromCodePoint(0x1f4f6),// new String[]{"signal_strength"}, 27, 19, false),
        Emojicon.fromCodePoint(0x1f4f3),// new String[]{"vibration_mode"}, 27, 16, false),
        Emojicon.fromCodePoint(0x1f4f4),// new String[]{"mobile_phone_off"}, 27, 17, false),
        Emojicon.fromCodePoints(0x2640, 0xfe0f),//), // }, new String[]{"female_sign"}, 53, 18, false),
        Emojicon.fromCodePoints(0x2642, 0xfe0f),//), // }, new String[]{"male_sign"}, 53, 19, false),
        Emojicon.fromCodePoints(0x2695, 0xfe0f),//), // }, new String[]{"medical_symbol", "staff_of_aesculapius"}, 53, 44, false),
        Emojicon.fromCodePoints(0x267e, 0xfe0f),//), // }, new String[]{"infinity"}, 53, 39, false),
        Emojicon.fromCodePoints(0x267b, 0xfe0f),//), // }, new String[]{"recycle"}, 53, 38, false),
        Emojicon.fromCodePoints(0x269c, 0xfe0f),//), // }, new String[]{"fleur_de_lis"}, 53, 49, false),
        Emojicon.fromCodePoint(0x1f531),// new String[]{"trident"}, 28, 20, false),
        Emojicon.fromCodePoint(0x1f4db),// new String[]{"name_badge"}, 26, 49, false),
        Emojicon.fromCodePoint(0x1f530),// new String[]{"beginner"}, 28, 19, false),
        Emojicon.fromCodePoint(0x2b55),// new String[]{"o"}, 55, 43, false),
        Emojicon.fromCodePoint(0x2705),// new String[]{"white_check_mark"}, 54, 40, false),
        Emojicon.fromCodePoints(0x2611, 0xfe0f),//), // }, new String[]{"ballot_box_with_check"}, 52, 55, false),
        Emojicon.fromCodePoints(0x2714, 0xfe0f),//), // }, new String[]{"heavy_check_mark"}, 55, 12, false),
        Emojicon.fromCodePoints(0x2716, 0xfe0f),//), // }, new String[]{"heavy_multiplication_x"}, 55, 13, false),
        Emojicon.fromCodePoint(0x274c),// new String[]{"x"}, 55, 21, false),
        Emojicon.fromCodePoint(0x274e),// new String[]{"negative_squared_cross_mark"}, 55, 22, false),
        Emojicon.fromCodePoint(0x2795),// new String[]{"heavy_plus_sign"}, 55, 29, false),
        Emojicon.fromCodePoint(0x2796),// new String[]{"heavy_minus_sign"}, 55, 30, false),
        Emojicon.fromCodePoint(0x2797),// new String[]{"heavy_division_sign"}, 55, 31, false),
        Emojicon.fromCodePoint(0x27b0),// new String[]{"curly_loop"}, 55, 33, false),
        Emojicon.fromCodePoint(0x27bf),// new String[]{"loop"}, 55, 34, false),
        Emojicon.fromCodePoints(0x303d, 0xfe0f),//), // }, new String[]{"part_alternation_mark"}, 55, 45, false),
        Emojicon.fromCodePoints(0x2733, 0xfe0f),//), // }, new String[]{"eight_spoked_asterisk"}, 55, 17, false),
        Emojicon.fromCodePoints(0x2734, 0xfe0f),//), // }, new String[]{"eight_pointed_black_star"}, 55, 18, false),
        Emojicon.fromCodePoints(0x2747, 0xfe0f),//), // }, new String[]{"sparkle"}, 55, 20, false),
        Emojicon.fromCodePoints(0x203c, 0xfe0f),//), // }, new String[]{"bangbang"}, 52, 10, false),
        Emojicon.fromCodePoints(0x2049, 0xfe0f),//), // }, new String[]{"interrobang"}, 52, 11, false),
        Emojicon.fromCodePoint(0x2753),// new String[]{"question"}, 55, 23, false),
        Emojicon.fromCodePoint(0x2754),// new String[]{"grey_question"}, 55, 24, false),
        Emojicon.fromCodePoint(0x2755),// new String[]{"grey_exclamation"}, 55, 25, false),
        Emojicon.fromCodePoint(0x2757),// new String[]{"exclamation", "heavy_exclamation_mark"}, 55, 26, false),
        Emojicon.fromCodePoints(0x3030, 0xfe0f),//), // }, new String[]{"wavy_dash"}, 55, 44, false),
        Emojicon.fromCodePoints(0x00a9, 0xfe0f),//), // }, new String[]{"copyright"}, 0, 12, false),
        Emojicon.fromCodePoints(0x00ae, 0xfe0f),//), // }, new String[]{"registered"}, 0, 13, false),
        Emojicon.fromCodePoints(0x2122, 0xfe0f),//), // }, new String[]{"tm"}, 52, 12, false),
        Emojicon.fromCodePoints(0x0023, 0xfe0f, 0x20e3),//), // }, new String[]{"hash"}, 0, 0, false),
        Emojicon.fromCodePoints(0x002a, 0xfe0f, 0x20e3),//), // }, new String[]{"keycap_star"}, 0, 1, false),
        Emojicon.fromCodePoints(0x0030, 0xfe0f, 0x20e3),//), // }, new String[]{"zero"}, 0, 2, false),
        Emojicon.fromCodePoints(0x0031, 0xfe0f, 0x20e3),//), // }, new String[]{"one"}, 0, 3, false),
        Emojicon.fromCodePoints(0x0032, 0xfe0f, 0x20e3),//), // }, new String[]{"two"}, 0, 4, false),
        Emojicon.fromCodePoints(0x0033, 0xfe0f, 0x20e3),//), // }, new String[]{"three"}, 0, 5, false),
        Emojicon.fromCodePoints(0x0034, 0xfe0f, 0x20e3),//), // }, new String[]{"four"}, 0, 6, false),
        Emojicon.fromCodePoints(0x0035, 0xfe0f, 0x20e3),//), // }, new String[]{"five"}, 0, 7, false),
        Emojicon.fromCodePoints(0x0036, 0xfe0f, 0x20e3),//), // }, new String[]{"six"}, 0, 8, false),
        Emojicon.fromCodePoints(0x0037, 0xfe0f, 0x20e3),//), // }, new String[]{"seven"}, 0, 9, false),
        Emojicon.fromCodePoints(0x0038, 0xfe0f, 0x20e3),//), // }, new String[]{"eight"}, 0, 10, false),
        Emojicon.fromCodePoints(0x0039, 0xfe0f, 0x20e3),//), // }, new String[]{"nine"}, 0, 11, false),
        Emojicon.fromCodePoint(0x1f51f),// new String[]{"keycap_ten"}, 28, 2, false),
        Emojicon.fromCodePoint(0x1f520),// new String[]{"capital_abcd"}, 28, 3, false),
        Emojicon.fromCodePoint(0x1f521),// new String[]{"abcd"}, 28, 4, false),
        Emojicon.fromCodePoint(0x1f522),// new String[]{"1234"}, 28, 5, false),
        Emojicon.fromCodePoint(0x1f523),// new String[]{"symbols"}, 28, 6, false),
        Emojicon.fromCodePoint(0x1f524),// new String[]{"abc"}, 28, 7, false),
        Emojicon.fromCodePoints(0x1f170, 0xfe0f),//), // }, new String[]{"a"}, 0, 16, false),
        Emojicon.fromCodePoint(0x1f18e),// new String[]{"ab"}, 0, 20, false),
        Emojicon.fromCodePoints(0x1f171, 0xfe0f),//), // }, new String[]{"b"}, 0, 17, false),
        Emojicon.fromCodePoint(0x1f191),// new String[]{"cl"}, 0, 21, false),
        Emojicon.fromCodePoint(0x1f192),// new String[]{"cool"}, 0, 22, false),
        Emojicon.fromCodePoint(0x1f193),// new String[]{"free"}, 0, 23, false),
        Emojicon.fromCodePoints(0x2139, 0xfe0f),//), // }, new String[]{"information_source"}, 52, 13, false),
        Emojicon.fromCodePoint(0x1f194),// new String[]{"id"}, 0, 24, false),
        Emojicon.fromCodePoints(0x24c2, 0xfe0f),//), // }, new String[]{"m"}, 52, 40, false),
        Emojicon.fromCodePoint(0x1f195),// new String[]{"new"}, 0, 25, false),
        Emojicon.fromCodePoint(0x1f196),// new String[]{"ng"}, 0, 26, false),
        Emojicon.fromCodePoints(0x1f17e, 0xfe0f),//), // }, new String[]{"o2"}, 0, 18, false),
        Emojicon.fromCodePoint(0x1f197),// new String[]{"ok"}, 0, 27, false),
        Emojicon.fromCodePoints(0x1f17f, 0xfe0f),//), // }, new String[]{"parking"}, 0, 19, false),
        Emojicon.fromCodePoint(0x1f198),// new String[]{"sos"}, 0, 28, false),
        Emojicon.fromCodePoint(0x1f199),// new String[]{"up"}, 0, 29, false),
        Emojicon.fromCodePoint(0x1f19a),// new String[]{"vs"}, 0, 30, false),
        Emojicon.fromCodePoint(0x1f201),// new String[]{"koko"}, 5, 4, false),
        Emojicon.fromCodePoints(0x1f202, 0xfe0f),//), // }, new String[]{"sa"}, 5, 5, false),
        Emojicon.fromCodePoints(0x1f237, 0xfe0f),//), // }, new String[]{"u6708"}, 5, 13, false),
        Emojicon.fromCodePoint(0x1f236),// new String[]{"u6709"}, 5, 12, false),
        Emojicon.fromCodePoint(0x1f22f),// new String[]{"u6307"}, 5, 7, false),
        Emojicon.fromCodePoint(0x1f250),// new String[]{"ideograph_advantage"}, 5, 17, false),
        Emojicon.fromCodePoint(0x1f239),// new String[]{"u5272"}, 5, 15, false),
        Emojicon.fromCodePoint(0x1f21a),// new String[]{"u7121"}, 5, 6, false),
        Emojicon.fromCodePoint(0x1f232),// new String[]{"u7981"}, 5, 8, false),
        Emojicon.fromCodePoint(0x1f251),// new String[]{"accept"}, 5, 18, false),
        Emojicon.fromCodePoint(0x1f238),// new String[]{"u7533"}, 5, 14, false),
        Emojicon.fromCodePoint(0x1f234),// new String[]{"u5408"}, 5, 10, false),
        Emojicon.fromCodePoint(0x1f233),// new String[]{"u7a7a"}, 5, 9, false),
        Emojicon.fromCodePoints(0x3297, 0xfe0f),//), // }, new String[]{"congratulations"}, 55, 46, false),
        Emojicon.fromCodePoints(0x3299, 0xfe0f),//), // }, new String[]{"secret"}, 55, 47, false),
        Emojicon.fromCodePoint(0x1f23a),// new String[]{"u55b6"}, 5, 16, false),
        Emojicon.fromCodePoint(0x1f235),// new String[]{"u6e80"}, 5, 11, false),
        Emojicon.fromCodePoint(0x1f534),// new String[]{"red_circle"}, 28, 23, false),
        Emojicon.fromCodePoint(0x1f7e0),// new String[]{"large_orange_circle"}, 37, 3, false),
        Emojicon.fromCodePoint(0x1f7e1),// new String[]{"large_yellow_circle"}, 37, 4, false),
        Emojicon.fromCodePoint(0x1f7e2),// new String[]{"large_green_circle"}, 37, 5, false),
        Emojicon.fromCodePoint(0x1f535),// new String[]{"large_blue_circle"}, 28, 24, false),
        Emojicon.fromCodePoint(0x1f7e3),// new String[]{"large_purple_circle"}, 37, 6, false),
        Emojicon.fromCodePoint(0x1f7e4),// new String[]{"large_brown_circle"}, 37, 7, false),
        Emojicon.fromCodePoint(0x26ab),// new String[]{"black_circle"}, 53, 53, false),
        Emojicon.fromCodePoint(0x26aa),// new String[]{"white_circle"}, 53, 52, false),
        Emojicon.fromCodePoint(0x1f7e5),// new String[]{"large_red_square"}, 37, 8, false),
        Emojicon.fromCodePoint(0x1f7e7),// new String[]{"large_orange_square"}, 37, 10, false),
        Emojicon.fromCodePoint(0x1f7e8),// new String[]{"large_yellow_square"}, 37, 11, false),
        Emojicon.fromCodePoint(0x1f7e9),// new String[]{"large_green_square"}, 37, 12, false),
        Emojicon.fromCodePoint(0x1f7e6),// new String[]{"large_blue_square"}, 37, 9, false),
        Emojicon.fromCodePoint(0x1f7ea),// new String[]{"large_purple_square"}, 37, 13, false),
        Emojicon.fromCodePoint(0x1f7eb),// new String[]{"large_brown_square"}, 37, 14, false),
        Emojicon.fromCodePoint(0x2b1b),// new String[]{"black_large_square"}, 55, 40, false),
        Emojicon.fromCodePoint(0x2b1c),// new String[]{"white_large_square"}, 55, 41, false),
        Emojicon.fromCodePoints(0x25fc, 0xfe0f),//), // }, new String[]{"black_medium_square"}, 52, 46, false),
        Emojicon.fromCodePoints(0x25fb, 0xfe0f),//), // }, new String[]{"white_medium_square"}, 52, 45, false),
        Emojicon.fromCodePoint(0x25fe),// new String[]{"black_medium_small_square"}, 52, 48, false),
        Emojicon.fromCodePoint(0x25fd),// new String[]{"white_medium_small_square"}, 52, 47, false),
        Emojicon.fromCodePoints(0x25aa, 0xfe0f),//), // }, new String[]{"black_small_square"}, 52, 41, false),
        Emojicon.fromCodePoints(0x25ab, 0xfe0f),//), // }, new String[]{"white_small_square"}, 52, 42, false),
        Emojicon.fromCodePoint(0x1f536),// new String[]{"large_orange_diamond"}, 28, 25, false),
        Emojicon.fromCodePoint(0x1f537),// new String[]{"large_blue_diamond"}, 28, 26, false),
        Emojicon.fromCodePoint(0x1f538),// new String[]{"small_orange_diamond"}, 28, 27, false),
        Emojicon.fromCodePoint(0x1f539),// new String[]{"small_blue_diamond"}, 28, 28, false),
        Emojicon.fromCodePoint(0x1f53a),// new String[]{"small_red_triangle"}, 28, 29, false),
        Emojicon.fromCodePoint(0x1f53b),// new String[]{"small_red_triangle_down"}, 28, 30, false),
        Emojicon.fromCodePoint(0x1f4a0),// new String[]{"diamond_shape_with_a_dot_inside"}, 25, 42, false),
        Emojicon.fromCodePoint(0x1f518),// new String[]{"radio_button"}, 27, 52, false),
        Emojicon.fromCodePoint(0x1f533),// new String[]{"white_square_button"}, 28, 22, false),
        Emojicon.fromCodePoint(0x1f532),// new String[]{"black_square_button"}, 28, 21, false)
    };
}
